
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Dec  1 2024 17:24:17 MST (Dec  2 2024 00:24:17 UTC)

// Verification Directory fv/uart_can_bridge 

module uart_can_bridge(clock, reset, Serial_in, Can_rx, Bridge_Can_out,
     Bridge_Serial_out, R_byte, T_byte);
  input clock, reset, Serial_in, Can_rx, R_byte, T_byte;
  output Bridge_Can_out, Bridge_Serial_out;
  wire clock, reset, Serial_in, Can_rx, R_byte, T_byte;
  wire Bridge_Can_out, Bridge_Serial_out;
  wire [11:0] Can_ID_Bus;
  wire [63:0] can_tx_data_bus;
  wire [7:0] uart_rx_data_bus;
  wire [7:0] uart_tx_data_Bus;
  wire [2:0] can_rx_inst_next_state;
  wire [2:0] can_rx_inst_state;
  wire [6:0] can_rx_inst_bit_count;
  wire [2:0] can_index;
  wire [7:0] Can_rx_data_Bus;
  wire [106:0] can_rx_inst_shift_reg;
  wire Can_out, Load_XMT_datareg, Load_frame_datareg, Serial_out,
       can_data_ready, can_rx_inst_n_1019, n_1, n_2;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_114, n_115, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_123, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_133;
  wire n_134, n_135, n_136, n_137, n_138, n_139, n_140, n_141;
  wire n_142, n_143, n_144, n_145, n_146, n_147, n_148, n_149;
  wire n_150, n_151, n_152, n_153, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181;
  wire n_182, n_183, n_184, n_185, n_186, n_187, n_188, n_193;
  wire n_194, n_199, n_200, n_201, n_202, n_203, n_204, n_205;
  wire n_206, n_207, n_208, n_209, n_210, n_211, n_212, n_213;
  wire n_214, n_215, n_216, n_217, n_218, n_219, n_220, n_221;
  wire n_222, n_223, n_224, n_225, n_226, n_227, n_228, n_229;
  wire n_230, n_231, n_232, n_233, n_234, n_235, n_236, n_241;
  wire n_242, n_243, n_244, n_250, n_251, uart_data_ready;
  assign can_rx_inst_next_state[1] = 1'b0;
  assign can_rx_inst_next_state[2] = 1'b0;
  assign can_rx_inst_next_state[0] = 1'b0;
  can_tx can_tx_inst(.clock (clock), .Frame_ready (Can_ID_Bus[0]),
       .Load_frame_datareg (Load_frame_datareg), .T_frame
       (Can_ID_Bus[0]), .reset (reset), .Can_ID_Bus ({2'b0,
       Can_ID_Bus[0], 5'b0, Can_ID_Bus[0], Can_ID_Bus[0], 1'b0,
       Can_ID_Bus[0]}), .can_tx_data_bus (can_tx_data_bus), .Can_out
       (Can_out));
  uart_rx uart_rx_inst(.clock (clock), .reset (reset), .R_byte
       (R_byte), .Serial_in (Serial_in), .uart_rx_data_bus
       (uart_rx_data_bus), .uart_data_ready (uart_data_ready));
  uart_tx uart_tx_inst(.clock (clock), .Byte_ready (1'b1),
       .Load_XMT_datareg (Load_XMT_datareg), .T_byte (T_byte), .reset
       (reset), .uart_tx_data_Bus (uart_tx_data_Bus), .Serial_out
       (Serial_out));
  OR2X1 g2058__2398(.A (n_214), .B (n_236), .Z
       (can_rx_inst_next_state[0]));
  MUX2X1 g2059__5107(.A (n_233), .B (n_235), .S (can_rx_inst_state[0]),
       .Z (n_236));
  NAND3X1 g2060__6260(.A (n_244), .B (n_230), .C (n_208), .Z
       (can_rx_inst_next_state[2]));
  NAND3X1 g2061__4319(.A (n_234), .B (n_231), .C (n_206), .Z
       (can_rx_inst_next_state[1]));
  NAND3X1 g2062__8428(.A (n_228), .B (n_227), .C (n_210), .Z (n_235));
  NAND2X1 g2063__5526(.A (n_232), .B (can_rx_inst_state[0]), .Z
       (n_234));
  AND2X1 g2064__6783(.A (n_226), .B (n_219), .Z (n_233));
  NAND2X1 g2065__3680(.A (n_225), .B (n_207), .Z (n_232));
  NAND2X1 g2066__1617(.A (n_205), .B (n_229), .Z (n_231));
  NAND3X1 g2067__2802(.A (n_205), .B (can_rx_inst_state[0]), .C
       (n_224), .Z (n_230));
  NAND2X1 g2068__1705(.A (can_rx_inst_state[0]), .B (n_224), .Z
       (n_229));
  NAND2X1 g2069__5122(.A (n_205), .B (n_223), .Z (n_228));
  OR2X1 g2070__8246(.A (n_220), .B (n_244), .Z (n_227));
  NAND2X1 g2071__7098(.A (n_204), .B (n_222), .Z (n_226));
  OR2X1 g2072__6131(.A (n_221), .B (n_244), .Z (n_225));
  INVX2 g2073(.A (n_224), .Z (n_223));
  NAND3X1 g2074__1881(.A (n_215), .B (n_203), .C (n_199), .Z (n_222));
  NAND2X1 g2075__5115(.A (n_200), .B (n_216), .Z (n_224));
  INVX2 g2076(.A (n_220), .Z (n_221));
  NAND2X1 g2077__7482(.A (n_200), .B (n_217), .Z (n_219));
  NOR2X1 g2078__4733(.A (n_200), .B (n_218), .Z (n_220));
  NOR2X1 g2079__6161(.A (can_rx_inst_bit_count[5]), .B (n_213), .Z
       (n_218));
  NAND2X1 g2080__9315(.A (n_212), .B (R_byte), .Z (n_217));
  NAND2X1 g2081__9945(.A (n_215), .B (R_byte), .Z (n_216));
  NOR2X1 g2082__2883(.A (Can_rx), .B (n_243), .Z (n_214));
  NAND2X1 g2083__2346(.A (can_rx_inst_n_1019), .B (n_202), .Z (n_215));
  INVX2 g2084(.A (n_241), .Z (n_213));
  OR2X1 g2085__1666(.A (n_209), .B (n_242), .Z (n_212));
  NAND2X1 g2086__7410(.A (n_211), .B (can_rx_inst_bit_count[4]), .Z
       (n_241));
  INVX2 g2087(.A (n_211), .Z (can_rx_inst_n_1019));
  OR2X1 g2088__6417(.A (R_byte), .B (n_250), .Z (n_210));
  NOR2X1 g2089__5477(.A (n_8), .B (n_251), .Z (n_209));
  OR2X1 g2090__2398(.A (can_rx_inst_state[0]), .B (n_250), .Z (n_243));
  NOR2X1 g2091__5107(.A (n_251), .B (n_201), .Z (n_211));
  NAND3X1 g2092__6260(.A (can_rx_inst_state[2]), .B (n_6), .C (n_5), .Z
       (n_208));
  OR2X1 g2093__4319(.A (n_5), .B (n_250), .Z (n_207));
  NAND3X1 g2094__8428(.A (can_rx_inst_state[1]), .B (n_6), .C (n_5), .Z
       (n_206));
  NAND2X1 g2095__5526(.A (n_202), .B (n_201), .Z (n_242));
  INVX2 g2096(.A (n_205), .Z (n_204));
  INVX2 g2097(.A (n_203), .Z (n_244));
  DFFQSRX1 Bridge_Can_out_reg(.SETB (1'b1), .RESETB (n_4), .CLK
       (clock), .D (Can_out), .Q (Bridge_Can_out));
  DFFQSRX1 Bridge_Serial_out_reg(.SETB (1'b1), .RESETB (n_4), .CLK
       (clock), .D (Serial_out), .Q (Bridge_Serial_out));
  NOR2X1 g2100__6783(.A (n_193), .B (can_rx_inst_state[2]), .Z (n_205));
  NOR2X1 g2101__3680(.A (n_194), .B (can_rx_inst_state[1]), .Z (n_203));
  INVX2 g2103(.A (n_200), .Z (n_199));
  NOR2X1 g2104__1617(.A (can_rx_inst_bit_count[5]), .B
       (can_rx_inst_bit_count[4]), .Z (n_202));
  NAND2X1 g2105__2802(.A (can_rx_inst_bit_count[3]), .B
       (can_rx_inst_bit_count[2]), .Z (n_201));
  NAND2X1 g2108__5122(.A (can_rx_inst_bit_count[6]), .B (R_byte), .Z
       (n_200));
  INVX2 g2109(.A (reset), .Z (n_4));
  INVX2 g2110(.A (R_byte), .Z (n_5));
  INVX2 g2111(.A (can_rx_inst_bit_count[3]), .Z (n_8));
  INVX2 g2112(.A (can_rx_inst_state[2]), .Z (n_194));
  INVX2 g2113(.A (can_rx_inst_state[1]), .Z (n_193));
  INVX2 g2114(.A (can_rx_inst_state[0]), .Z (n_6));
  DFFQSRX1 \Can_ID_Bus_reg[0] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_123), .Q (Can_ID_Bus[0]));
  DFFQSRX1 Load_XMT_datareg_reg(.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (can_data_ready), .Q (Load_XMT_datareg));
  DFFQSRX1 Load_frame_datareg_reg(.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_117), .Q (Load_frame_datareg));
  DFFQSRX1 \can_index_reg[0] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_93), .Q (can_index[0]));
  DFFQSRX1 \can_index_reg[1] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_112), .Q (can_index[1]));
  DFFQSRX1 \can_index_reg[2] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_116), .Q (can_index[2]));
  DFFQSRX1 can_rx_inst_Can_data_ready_reg(.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_103), .Q (can_data_ready));
  DFFQSRX1 \can_rx_inst_Can_rx_data_Bus_reg[0] (.SETB (n_4), .RESETB
       (1'b1), .CLK (clock), .D (n_187), .Q (Can_rx_data_Bus[0]));
  DFFQSRX1 \can_rx_inst_Can_rx_data_Bus_reg[1] (.SETB (n_4), .RESETB
       (1'b1), .CLK (clock), .D (n_188), .Q (Can_rx_data_Bus[1]));
  DFFQSRX1 \can_rx_inst_Can_rx_data_Bus_reg[2] (.SETB (n_4), .RESETB
       (1'b1), .CLK (clock), .D (n_186), .Q (Can_rx_data_Bus[2]));
  DFFQSRX1 \can_rx_inst_Can_rx_data_Bus_reg[3] (.SETB (n_4), .RESETB
       (1'b1), .CLK (clock), .D (n_183), .Q (Can_rx_data_Bus[3]));
  DFFQSRX1 \can_rx_inst_Can_rx_data_Bus_reg[4] (.SETB (n_4), .RESETB
       (1'b1), .CLK (clock), .D (n_184), .Q (Can_rx_data_Bus[4]));
  DFFQSRX1 \can_rx_inst_Can_rx_data_Bus_reg[5] (.SETB (n_4), .RESETB
       (1'b1), .CLK (clock), .D (n_185), .Q (Can_rx_data_Bus[5]));
  DFFQSRX1 \can_rx_inst_Can_rx_data_Bus_reg[6] (.SETB (n_4), .RESETB
       (1'b1), .CLK (clock), .D (n_182), .Q (Can_rx_data_Bus[6]));
  DFFQSRX1 \can_rx_inst_Can_rx_data_Bus_reg[7] (.SETB (n_4), .RESETB
       (1'b1), .CLK (clock), .D (n_181), .Q (Can_rx_data_Bus[7]));
  DFFQSRX1 \can_rx_inst_bit_count_reg[0] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_125), .Q (can_rx_inst_bit_count[0]));
  DFFQSRX1 \can_rx_inst_bit_count_reg[1] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_174), .Q (can_rx_inst_bit_count[1]));
  DFFQSRX1 \can_rx_inst_bit_count_reg[2] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_173), .Q (can_rx_inst_bit_count[2]));
  DFFQSRX1 \can_rx_inst_bit_count_reg[3] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_172), .Q (can_rx_inst_bit_count[3]));
  DFFQSRX1 \can_rx_inst_bit_count_reg[4] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_171), .Q (can_rx_inst_bit_count[4]));
  DFFQSRX1 \can_rx_inst_bit_count_reg[5] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_170), .Q (can_rx_inst_bit_count[5]));
  DFFQSRX1 \can_rx_inst_bit_count_reg[6] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_180), .Q (can_rx_inst_bit_count[6]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[60] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_128), .Q (can_rx_inst_shift_reg[60]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[61] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_127), .Q (can_rx_inst_shift_reg[61]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[62] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_126), .Q (can_rx_inst_shift_reg[62]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[63] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_168), .Q (can_rx_inst_shift_reg[63]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[64] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_167), .Q (can_rx_inst_shift_reg[64]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[65] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_166), .Q (can_rx_inst_shift_reg[65]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[66] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_165), .Q (can_rx_inst_shift_reg[66]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[67] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_178), .Q (can_rx_inst_shift_reg[67]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[68] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_163), .Q (can_rx_inst_shift_reg[68]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[69] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_162), .Q (can_rx_inst_shift_reg[69]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[70] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_161), .Q (can_rx_inst_shift_reg[70]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[71] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_160), .Q (can_rx_inst_shift_reg[71]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[72] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_159), .Q (can_rx_inst_shift_reg[72]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[73] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_158), .Q (can_rx_inst_shift_reg[73]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[74] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_157), .Q (can_rx_inst_shift_reg[74]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[75] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_156), .Q (can_rx_inst_shift_reg[75]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[76] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_155), .Q (can_rx_inst_shift_reg[76]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[77] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_154), .Q (can_rx_inst_shift_reg[77]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[78] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_164), .Q (can_rx_inst_shift_reg[78]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[79] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_175), .Q (can_rx_inst_shift_reg[79]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[80] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_176), .Q (can_rx_inst_shift_reg[80]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[81] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_177), .Q (can_rx_inst_shift_reg[81]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[82] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_139), .Q (can_rx_inst_shift_reg[82]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[83] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_152), .Q (can_rx_inst_shift_reg[83]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[84] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_151), .Q (can_rx_inst_shift_reg[84]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[85] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_150), .Q (can_rx_inst_shift_reg[85]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[86] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_149), .Q (can_rx_inst_shift_reg[86]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[87] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_148), .Q (can_rx_inst_shift_reg[87]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[88] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_147), .Q (can_rx_inst_shift_reg[88]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[89] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_146), .Q (can_rx_inst_shift_reg[89]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[90] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_145), .Q (can_rx_inst_shift_reg[90]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[91] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_144), .Q (can_rx_inst_shift_reg[91]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[92] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_143), .Q (can_rx_inst_shift_reg[92]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[93] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_142), .Q (can_rx_inst_shift_reg[93]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[94] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_141), .Q (can_rx_inst_shift_reg[94]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[95] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_140), .Q (can_rx_inst_shift_reg[95]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[96] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_153), .Q (can_rx_inst_shift_reg[96]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[97] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_138), .Q (can_rx_inst_shift_reg[97]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[98] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_137), .Q (can_rx_inst_shift_reg[98]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[99] (.SETB (n_4), .RESETB (1'b1),
       .CLK (clock), .D (n_136), .Q (can_rx_inst_shift_reg[99]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[100] (.SETB (n_4), .RESETB
       (1'b1), .CLK (clock), .D (n_135), .Q
       (can_rx_inst_shift_reg[100]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[101] (.SETB (n_4), .RESETB
       (1'b1), .CLK (clock), .D (n_134), .Q
       (can_rx_inst_shift_reg[101]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[102] (.SETB (n_4), .RESETB
       (1'b1), .CLK (clock), .D (n_133), .Q
       (can_rx_inst_shift_reg[102]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[103] (.SETB (n_4), .RESETB
       (1'b1), .CLK (clock), .D (n_132), .Q
       (can_rx_inst_shift_reg[103]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[104] (.SETB (n_4), .RESETB
       (1'b1), .CLK (clock), .D (n_131), .Q
       (can_rx_inst_shift_reg[104]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[105] (.SETB (n_4), .RESETB
       (1'b1), .CLK (clock), .D (n_130), .Q
       (can_rx_inst_shift_reg[105]));
  DFFQSRX1 \can_rx_inst_shift_reg_reg[106] (.SETB (n_4), .RESETB
       (1'b1), .CLK (clock), .D (n_129), .Q
       (can_rx_inst_shift_reg[106]));
  DFFQSRX1 \can_rx_inst_state_reg[0] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (can_rx_inst_next_state[0]), .Q
       (can_rx_inst_state[0]));
  DFFQSRX1 \can_rx_inst_state_reg[1] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (can_rx_inst_next_state[1]), .Q
       (can_rx_inst_state[1]));
  DFFQSRX1 \can_rx_inst_state_reg[2] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (can_rx_inst_next_state[2]), .Q
       (can_rx_inst_state[2]));
  DFFQSRX1 \can_tx_data_bus_reg[0] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_38), .Q (can_tx_data_bus[0]));
  DFFQSRX1 \can_tx_data_bus_reg[1] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_37), .Q (can_tx_data_bus[1]));
  DFFQSRX1 \can_tx_data_bus_reg[2] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_36), .Q (can_tx_data_bus[2]));
  DFFQSRX1 \can_tx_data_bus_reg[3] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_64), .Q (can_tx_data_bus[3]));
  DFFQSRX1 \can_tx_data_bus_reg[4] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_35), .Q (can_tx_data_bus[4]));
  DFFQSRX1 \can_tx_data_bus_reg[5] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_34), .Q (can_tx_data_bus[5]));
  DFFQSRX1 \can_tx_data_bus_reg[6] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_33), .Q (can_tx_data_bus[6]));
  DFFQSRX1 \can_tx_data_bus_reg[7] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_32), .Q (can_tx_data_bus[7]));
  DFFQSRX1 \can_tx_data_bus_reg[8] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_31), .Q (can_tx_data_bus[8]));
  DFFQSRX1 \can_tx_data_bus_reg[9] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_30), .Q (can_tx_data_bus[9]));
  DFFQSRX1 \can_tx_data_bus_reg[10] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_92), .Q (can_tx_data_bus[10]));
  DFFQSRX1 \can_tx_data_bus_reg[11] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_91), .Q (can_tx_data_bus[11]));
  DFFQSRX1 \can_tx_data_bus_reg[12] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_90), .Q (can_tx_data_bus[12]));
  DFFQSRX1 \can_tx_data_bus_reg[13] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_89), .Q (can_tx_data_bus[13]));
  DFFQSRX1 \can_tx_data_bus_reg[14] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_88), .Q (can_tx_data_bus[14]));
  DFFQSRX1 \can_tx_data_bus_reg[15] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_87), .Q (can_tx_data_bus[15]));
  DFFQSRX1 \can_tx_data_bus_reg[16] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_86), .Q (can_tx_data_bus[16]));
  DFFQSRX1 \can_tx_data_bus_reg[17] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_85), .Q (can_tx_data_bus[17]));
  DFFQSRX1 \can_tx_data_bus_reg[18] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_84), .Q (can_tx_data_bus[18]));
  DFFQSRX1 \can_tx_data_bus_reg[19] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_83), .Q (can_tx_data_bus[19]));
  DFFQSRX1 \can_tx_data_bus_reg[20] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_82), .Q (can_tx_data_bus[20]));
  DFFQSRX1 \can_tx_data_bus_reg[21] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_81), .Q (can_tx_data_bus[21]));
  DFFQSRX1 \can_tx_data_bus_reg[22] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_80), .Q (can_tx_data_bus[22]));
  DFFQSRX1 \can_tx_data_bus_reg[23] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_98), .Q (can_tx_data_bus[23]));
  DFFQSRX1 \can_tx_data_bus_reg[24] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_78), .Q (can_tx_data_bus[24]));
  DFFQSRX1 \can_tx_data_bus_reg[25] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_77), .Q (can_tx_data_bus[25]));
  DFFQSRX1 \can_tx_data_bus_reg[26] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_76), .Q (can_tx_data_bus[26]));
  DFFQSRX1 \can_tx_data_bus_reg[27] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_75), .Q (can_tx_data_bus[27]));
  DFFQSRX1 \can_tx_data_bus_reg[28] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_74), .Q (can_tx_data_bus[28]));
  DFFQSRX1 \can_tx_data_bus_reg[29] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_73), .Q (can_tx_data_bus[29]));
  DFFQSRX1 \can_tx_data_bus_reg[30] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_72), .Q (can_tx_data_bus[30]));
  DFFQSRX1 \can_tx_data_bus_reg[31] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_71), .Q (can_tx_data_bus[31]));
  DFFQSRX1 \can_tx_data_bus_reg[32] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_70), .Q (can_tx_data_bus[32]));
  DFFQSRX1 \can_tx_data_bus_reg[33] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_69), .Q (can_tx_data_bus[33]));
  DFFQSRX1 \can_tx_data_bus_reg[34] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_68), .Q (can_tx_data_bus[34]));
  DFFQSRX1 \can_tx_data_bus_reg[35] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_67), .Q (can_tx_data_bus[35]));
  DFFQSRX1 \can_tx_data_bus_reg[36] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_66), .Q (can_tx_data_bus[36]));
  DFFQSRX1 \can_tx_data_bus_reg[37] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_65), .Q (can_tx_data_bus[37]));
  DFFQSRX1 \can_tx_data_bus_reg[38] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_63), .Q (can_tx_data_bus[38]));
  DFFQSRX1 \can_tx_data_bus_reg[39] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_62), .Q (can_tx_data_bus[39]));
  DFFQSRX1 \can_tx_data_bus_reg[40] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_61), .Q (can_tx_data_bus[40]));
  DFFQSRX1 \can_tx_data_bus_reg[41] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_94), .Q (can_tx_data_bus[41]));
  DFFQSRX1 \can_tx_data_bus_reg[42] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_96), .Q (can_tx_data_bus[42]));
  DFFQSRX1 \can_tx_data_bus_reg[43] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_18), .Q (can_tx_data_bus[43]));
  DFFQSRX1 \can_tx_data_bus_reg[44] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_58), .Q (can_tx_data_bus[44]));
  DFFQSRX1 \can_tx_data_bus_reg[45] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_57), .Q (can_tx_data_bus[45]));
  DFFQSRX1 \can_tx_data_bus_reg[46] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_56), .Q (can_tx_data_bus[46]));
  DFFQSRX1 \can_tx_data_bus_reg[47] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_55), .Q (can_tx_data_bus[47]));
  DFFQSRX1 \can_tx_data_bus_reg[48] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_54), .Q (can_tx_data_bus[48]));
  DFFQSRX1 \can_tx_data_bus_reg[49] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_53), .Q (can_tx_data_bus[49]));
  DFFQSRX1 \can_tx_data_bus_reg[50] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_52), .Q (can_tx_data_bus[50]));
  DFFQSRX1 \can_tx_data_bus_reg[51] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_51), .Q (can_tx_data_bus[51]));
  DFFQSRX1 \can_tx_data_bus_reg[52] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_50), .Q (can_tx_data_bus[52]));
  DFFQSRX1 \can_tx_data_bus_reg[53] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_49), .Q (can_tx_data_bus[53]));
  DFFQSRX1 \can_tx_data_bus_reg[54] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_48), .Q (can_tx_data_bus[54]));
  DFFQSRX1 \can_tx_data_bus_reg[55] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_47), .Q (can_tx_data_bus[55]));
  DFFQSRX1 \can_tx_data_bus_reg[56] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_46), .Q (can_tx_data_bus[56]));
  DFFQSRX1 \can_tx_data_bus_reg[57] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_45), .Q (can_tx_data_bus[57]));
  DFFQSRX1 \can_tx_data_bus_reg[58] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_44), .Q (can_tx_data_bus[58]));
  DFFQSRX1 \can_tx_data_bus_reg[59] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_43), .Q (can_tx_data_bus[59]));
  DFFQSRX1 \can_tx_data_bus_reg[60] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_42), .Q (can_tx_data_bus[60]));
  DFFQSRX1 \can_tx_data_bus_reg[61] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_39), .Q (can_tx_data_bus[61]));
  DFFQSRX1 \can_tx_data_bus_reg[62] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_41), .Q (can_tx_data_bus[62]));
  DFFQSRX1 \can_tx_data_bus_reg[63] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_40), .Q (can_tx_data_bus[63]));
  DFFQSRX1 \uart_tx_data_Bus_reg[0] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_29), .Q (uart_tx_data_Bus[0]));
  DFFQSRX1 \uart_tx_data_Bus_reg[1] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_28), .Q (uart_tx_data_Bus[1]));
  DFFQSRX1 \uart_tx_data_Bus_reg[2] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_27), .Q (uart_tx_data_Bus[2]));
  DFFQSRX1 \uart_tx_data_Bus_reg[3] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_25), .Q (uart_tx_data_Bus[3]));
  DFFQSRX1 \uart_tx_data_Bus_reg[4] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_24), .Q (uart_tx_data_Bus[4]));
  DFFQSRX1 \uart_tx_data_Bus_reg[5] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_23), .Q (uart_tx_data_Bus[5]));
  DFFQSRX1 \uart_tx_data_Bus_reg[6] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_22), .Q (uart_tx_data_Bus[6]));
  DFFQSRX1 \uart_tx_data_Bus_reg[7] (.SETB (n_4), .RESETB (1'b1), .CLK
       (clock), .D (n_26), .Q (uart_tx_data_Bus[7]));
  MUX2X1 g3243__6131(.A (Can_rx_data_Bus[1]), .B
       (can_rx_inst_shift_reg[61]), .S (n_179), .Z (n_188));
  MUX2X1 g3244__1881(.A (Can_rx_data_Bus[0]), .B
       (can_rx_inst_shift_reg[60]), .S (n_179), .Z (n_187));
  MUX2X1 g3245__5115(.A (Can_rx_data_Bus[2]), .B
       (can_rx_inst_shift_reg[62]), .S (n_179), .Z (n_186));
  MUX2X1 g3247__7482(.A (Can_rx_data_Bus[5]), .B
       (can_rx_inst_shift_reg[65]), .S (n_179), .Z (n_185));
  MUX2X1 g3248__4733(.A (Can_rx_data_Bus[4]), .B
       (can_rx_inst_shift_reg[64]), .S (n_179), .Z (n_184));
  MUX2X1 g3249__6161(.A (Can_rx_data_Bus[3]), .B
       (can_rx_inst_shift_reg[63]), .S (n_179), .Z (n_183));
  MUX2X1 g3250__9315(.A (Can_rx_data_Bus[6]), .B
       (can_rx_inst_shift_reg[66]), .S (n_179), .Z (n_182));
  MUX2X1 g3251__9945(.A (Can_rx_data_Bus[7]), .B
       (can_rx_inst_shift_reg[67]), .S (n_179), .Z (n_181));
  NAND2X1 g3279__2883(.A (n_110), .B (n_169), .Z (n_180));
  MUX2X1 g3306__2346(.A (can_rx_inst_shift_reg[67]), .B
       (can_rx_inst_shift_reg[68]), .S (n_2), .Z (n_178));
  MUX2X1 g3307__1666(.A (can_rx_inst_shift_reg[81]), .B
       (can_rx_inst_shift_reg[82]), .S (n_2), .Z (n_177));
  MUX2X1 g3308__7410(.A (can_rx_inst_shift_reg[80]), .B
       (can_rx_inst_shift_reg[81]), .S (n_2), .Z (n_176));
  MUX2X1 g3309__6417(.A (can_rx_inst_shift_reg[79]), .B
       (can_rx_inst_shift_reg[80]), .S (n_2), .Z (n_175));
  NAND2X1 g3310__5477(.A (n_105), .B (n_124), .Z (n_174));
  NAND2X1 g3311__2398(.A (n_106), .B (n_122), .Z (n_173));
  NAND2X1 g3312__5107(.A (n_107), .B (n_120), .Z (n_172));
  NAND2X1 g3313__6260(.A (n_108), .B (n_119), .Z (n_171));
  NAND2X1 g3314__4319(.A (n_109), .B (n_118), .Z (n_170));
  NAND2X1 g3315__8428(.A (n_2), .B (n_115), .Z (n_169));
  MUX2X1 g3316__5526(.A (can_rx_inst_shift_reg[63]), .B
       (can_rx_inst_shift_reg[64]), .S (n_2), .Z (n_168));
  MUX2X1 g3317__6783(.A (can_rx_inst_shift_reg[64]), .B
       (can_rx_inst_shift_reg[65]), .S (n_2), .Z (n_167));
  MUX2X1 g3318__3680(.A (can_rx_inst_shift_reg[65]), .B
       (can_rx_inst_shift_reg[66]), .S (n_2), .Z (n_166));
  MUX2X1 g3319__1617(.A (can_rx_inst_shift_reg[66]), .B
       (can_rx_inst_shift_reg[67]), .S (n_2), .Z (n_165));
  MUX2X1 g3320__2802(.A (can_rx_inst_shift_reg[78]), .B
       (can_rx_inst_shift_reg[79]), .S (n_2), .Z (n_164));
  MUX2X1 g3321__1705(.A (can_rx_inst_shift_reg[68]), .B
       (can_rx_inst_shift_reg[69]), .S (n_2), .Z (n_163));
  MUX2X1 g3322__5122(.A (can_rx_inst_shift_reg[69]), .B
       (can_rx_inst_shift_reg[70]), .S (n_2), .Z (n_162));
  MUX2X1 g3323__8246(.A (can_rx_inst_shift_reg[70]), .B
       (can_rx_inst_shift_reg[71]), .S (n_2), .Z (n_161));
  MUX2X1 g3324__7098(.A (can_rx_inst_shift_reg[71]), .B
       (can_rx_inst_shift_reg[72]), .S (n_2), .Z (n_160));
  MUX2X1 g3325__6131(.A (can_rx_inst_shift_reg[72]), .B
       (can_rx_inst_shift_reg[73]), .S (n_2), .Z (n_159));
  MUX2X1 g3326__1881(.A (can_rx_inst_shift_reg[73]), .B
       (can_rx_inst_shift_reg[74]), .S (n_2), .Z (n_158));
  MUX2X1 g3327__5115(.A (can_rx_inst_shift_reg[74]), .B
       (can_rx_inst_shift_reg[75]), .S (n_2), .Z (n_157));
  MUX2X1 g3328__7482(.A (can_rx_inst_shift_reg[75]), .B
       (can_rx_inst_shift_reg[76]), .S (n_2), .Z (n_156));
  MUX2X1 g3329__4733(.A (can_rx_inst_shift_reg[76]), .B
       (can_rx_inst_shift_reg[77]), .S (n_2), .Z (n_155));
  MUX2X1 g3330__6161(.A (can_rx_inst_shift_reg[77]), .B
       (can_rx_inst_shift_reg[78]), .S (n_2), .Z (n_154));
  NOR2X1 g3334__9315(.A (n_242), .B (n_121), .Z (n_179));
  MUX2X1 g3335__9945(.A (can_rx_inst_shift_reg[96]), .B
       (can_rx_inst_shift_reg[97]), .S (n_2), .Z (n_153));
  MUX2X1 g3336__2883(.A (can_rx_inst_shift_reg[83]), .B
       (can_rx_inst_shift_reg[84]), .S (n_2), .Z (n_152));
  MUX2X1 g3337__2346(.A (can_rx_inst_shift_reg[84]), .B
       (can_rx_inst_shift_reg[85]), .S (n_2), .Z (n_151));
  MUX2X1 g3338__1666(.A (can_rx_inst_shift_reg[85]), .B
       (can_rx_inst_shift_reg[86]), .S (n_2), .Z (n_150));
  MUX2X1 g3339__7410(.A (can_rx_inst_shift_reg[86]), .B
       (can_rx_inst_shift_reg[87]), .S (n_2), .Z (n_149));
  MUX2X1 g3340__6417(.A (can_rx_inst_shift_reg[87]), .B
       (can_rx_inst_shift_reg[88]), .S (n_2), .Z (n_148));
  MUX2X1 g3341__5477(.A (can_rx_inst_shift_reg[88]), .B
       (can_rx_inst_shift_reg[89]), .S (n_2), .Z (n_147));
  MUX2X1 g3342__2398(.A (can_rx_inst_shift_reg[89]), .B
       (can_rx_inst_shift_reg[90]), .S (n_2), .Z (n_146));
  MUX2X1 g3343__5107(.A (can_rx_inst_shift_reg[90]), .B
       (can_rx_inst_shift_reg[91]), .S (n_2), .Z (n_145));
  MUX2X1 g3344__6260(.A (can_rx_inst_shift_reg[91]), .B
       (can_rx_inst_shift_reg[92]), .S (n_2), .Z (n_144));
  MUX2X1 g3345__4319(.A (can_rx_inst_shift_reg[92]), .B
       (can_rx_inst_shift_reg[93]), .S (n_2), .Z (n_143));
  MUX2X1 g3346__8428(.A (can_rx_inst_shift_reg[93]), .B
       (can_rx_inst_shift_reg[94]), .S (n_2), .Z (n_142));
  MUX2X1 g3347__5526(.A (can_rx_inst_shift_reg[94]), .B
       (can_rx_inst_shift_reg[95]), .S (n_2), .Z (n_141));
  MUX2X1 g3348__6783(.A (can_rx_inst_shift_reg[95]), .B
       (can_rx_inst_shift_reg[96]), .S (n_2), .Z (n_140));
  MUX2X1 g3349__3680(.A (can_rx_inst_shift_reg[82]), .B
       (can_rx_inst_shift_reg[83]), .S (n_2), .Z (n_139));
  MUX2X1 g3350__1617(.A (can_rx_inst_shift_reg[97]), .B
       (can_rx_inst_shift_reg[98]), .S (n_2), .Z (n_138));
  MUX2X1 g3351__2802(.A (can_rx_inst_shift_reg[98]), .B
       (can_rx_inst_shift_reg[99]), .S (n_2), .Z (n_137));
  MUX2X1 g3352__1705(.A (can_rx_inst_shift_reg[99]), .B
       (can_rx_inst_shift_reg[100]), .S (n_2), .Z (n_136));
  MUX2X1 g3353__5122(.A (can_rx_inst_shift_reg[100]), .B
       (can_rx_inst_shift_reg[101]), .S (n_2), .Z (n_135));
  MUX2X1 g3354__8246(.A (can_rx_inst_shift_reg[101]), .B
       (can_rx_inst_shift_reg[102]), .S (n_2), .Z (n_134));
  MUX2X1 g3355__7098(.A (can_rx_inst_shift_reg[102]), .B
       (can_rx_inst_shift_reg[103]), .S (n_2), .Z (n_133));
  MUX2X1 g3356__6131(.A (can_rx_inst_shift_reg[103]), .B
       (can_rx_inst_shift_reg[104]), .S (n_2), .Z (n_132));
  MUX2X1 g3357__1881(.A (can_rx_inst_shift_reg[104]), .B
       (can_rx_inst_shift_reg[105]), .S (n_2), .Z (n_131));
  MUX2X1 g3358__5115(.A (can_rx_inst_shift_reg[105]), .B
       (can_rx_inst_shift_reg[106]), .S (n_2), .Z (n_130));
  MUX2X1 g3359__7482(.A (can_rx_inst_shift_reg[106]), .B (Can_rx), .S
       (n_2), .Z (n_129));
  MUX2X1 g3360__4733(.A (can_rx_inst_shift_reg[60]), .B
       (can_rx_inst_shift_reg[61]), .S (n_2), .Z (n_128));
  MUX2X1 g3361__6161(.A (can_rx_inst_shift_reg[61]), .B
       (can_rx_inst_shift_reg[62]), .S (n_2), .Z (n_127));
  MUX2X1 g3362__9315(.A (can_rx_inst_shift_reg[62]), .B
       (can_rx_inst_shift_reg[63]), .S (n_2), .Z (n_126));
  MUX2X1 g3363__9945(.A (n_2), .B (n_99), .S
       (can_rx_inst_bit_count[0]), .Z (n_125));
  NAND2X1 g3364__2883(.A (n_2), .B (n_59), .Z (n_124));
  OR2X1 g3365__2346(.A (Can_ID_Bus[0]), .B (n_114), .Z (n_123));
  OR2X1 g3366__1666(.A (n_19), .B (n_1), .Z (n_122));
  OR2X1 g3367__7410(.A (n_244), .B (n_104), .Z (n_121));
  NAND2X1 g3370__6417(.A (n_2), .B (n_111), .Z (n_120));
  OR2X1 g3371__5477(.A (n_21), .B (n_1), .Z (n_119));
  OR2X1 g3372__2398(.A (n_20), .B (n_1), .Z (n_118));
  OR2X1 g3373__5107(.A (n_11), .B (n_114), .Z (n_117));
  NOR2X1 g3374__6260(.A (n_102), .B (n_114), .Z (n_116));
  XOR2X1 g3375__4319(.A (can_rx_inst_bit_count[6]), .B (n_60), .Z
       (n_115));
  INVX8 g3427(.A (n_1), .Z (n_2));
  NOR2X1 g3428__8428(.A (n_79), .B (n_100), .Z (n_112));
  XOR2X1 g3429__5526(.A (can_rx_inst_bit_count[3]), .B (n_16), .Z
       (n_111));
  NAND2X1 g3430__6783(.A (n_99), .B (can_rx_inst_bit_count[6]), .Z
       (n_110));
  NAND2X1 g3431__3680(.A (n_99), .B (can_rx_inst_bit_count[5]), .Z
       (n_109));
  NAND2X1 g3432__1617(.A (n_99), .B (can_rx_inst_bit_count[4]), .Z
       (n_108));
  NAND2X1 g3433__2802(.A (n_99), .B (can_rx_inst_bit_count[3]), .Z
       (n_107));
  NAND2X1 g3434__1705(.A (n_99), .B (can_rx_inst_bit_count[2]), .Z
       (n_106));
  NAND2X1 g3435__5122(.A (n_99), .B (can_rx_inst_bit_count[1]), .Z
       (n_105));
  NAND3X1 g3436__8246(.A (n_97), .B (n_6), .C
       (can_rx_inst_bit_count[6]), .Z (n_104));
  NAND2X1 g3437__7098(.A (n_9), .B (n_95), .Z (n_103));
  NOR2X1 g3438__6131(.A (can_index[2]), .B (n_100), .Z (n_102));
  AND2X1 g3459__1881(.A (n_100), .B (can_index[2]), .Z (n_114));
  NAND3X1 g3470__5115(.A (n_243), .B (n_14), .C (R_byte), .Z (n_1));
  MUX2X1 g3471__7482(.A (can_tx_data_bus[23]), .B
       (can_tx_data_bus[15]), .S (uart_data_ready), .Z (n_98));
  NAND3X1 g3472__4733(.A (n_251), .B (n_8), .C (n_7), .Z (n_97));
  MUX2X1 g3473__6161(.A (can_tx_data_bus[42]), .B
       (can_tx_data_bus[34]), .S (uart_data_ready), .Z (n_96));
  NAND3X1 g3474__9315(.A (n_15), .B (n_6), .C (R_byte), .Z (n_95));
  MUX2X1 g3475__9945(.A (can_tx_data_bus[41]), .B
       (can_tx_data_bus[33]), .S (uart_data_ready), .Z (n_94));
  NOR2X1 g3476__2883(.A (n_10), .B (n_13), .Z (n_93));
  MUX2X1 g3477__2346(.A (can_tx_data_bus[10]), .B (can_tx_data_bus[2]),
       .S (uart_data_ready), .Z (n_92));
  MUX2X1 g3478__1666(.A (can_tx_data_bus[11]), .B (can_tx_data_bus[3]),
       .S (uart_data_ready), .Z (n_91));
  MUX2X1 g3479__7410(.A (can_tx_data_bus[12]), .B (can_tx_data_bus[4]),
       .S (uart_data_ready), .Z (n_90));
  MUX2X1 g3480__6417(.A (can_tx_data_bus[13]), .B (can_tx_data_bus[5]),
       .S (uart_data_ready), .Z (n_89));
  MUX2X1 g3481__5477(.A (can_tx_data_bus[14]), .B (can_tx_data_bus[6]),
       .S (uart_data_ready), .Z (n_88));
  MUX2X1 g3482__2398(.A (can_tx_data_bus[15]), .B (can_tx_data_bus[7]),
       .S (uart_data_ready), .Z (n_87));
  MUX2X1 g3483__5107(.A (can_tx_data_bus[16]), .B (can_tx_data_bus[8]),
       .S (uart_data_ready), .Z (n_86));
  MUX2X1 g3484__6260(.A (can_tx_data_bus[17]), .B (can_tx_data_bus[9]),
       .S (uart_data_ready), .Z (n_85));
  MUX2X1 g3485__4319(.A (can_tx_data_bus[18]), .B
       (can_tx_data_bus[10]), .S (uart_data_ready), .Z (n_84));
  MUX2X1 g3486__8428(.A (can_tx_data_bus[19]), .B
       (can_tx_data_bus[11]), .S (uart_data_ready), .Z (n_83));
  MUX2X1 g3487__5526(.A (can_tx_data_bus[20]), .B
       (can_tx_data_bus[12]), .S (uart_data_ready), .Z (n_82));
  MUX2X1 g3488__6783(.A (can_tx_data_bus[21]), .B
       (can_tx_data_bus[13]), .S (uart_data_ready), .Z (n_81));
  MUX2X1 g3489__3680(.A (can_tx_data_bus[22]), .B
       (can_tx_data_bus[14]), .S (uart_data_ready), .Z (n_80));
  NOR2X1 g3490__1617(.A (can_index[1]), .B (n_13), .Z (n_79));
  MUX2X1 g3491__2802(.A (can_tx_data_bus[24]), .B
       (can_tx_data_bus[16]), .S (uart_data_ready), .Z (n_78));
  MUX2X1 g3492__1705(.A (can_tx_data_bus[25]), .B
       (can_tx_data_bus[17]), .S (uart_data_ready), .Z (n_77));
  MUX2X1 g3493__5122(.A (can_tx_data_bus[26]), .B
       (can_tx_data_bus[18]), .S (uart_data_ready), .Z (n_76));
  MUX2X1 g3494__8246(.A (can_tx_data_bus[27]), .B
       (can_tx_data_bus[19]), .S (uart_data_ready), .Z (n_75));
  MUX2X1 g3495__7098(.A (can_tx_data_bus[28]), .B
       (can_tx_data_bus[20]), .S (uart_data_ready), .Z (n_74));
  MUX2X1 g3496__6131(.A (can_tx_data_bus[29]), .B
       (can_tx_data_bus[21]), .S (uart_data_ready), .Z (n_73));
  MUX2X1 g3497__1881(.A (can_tx_data_bus[30]), .B
       (can_tx_data_bus[22]), .S (uart_data_ready), .Z (n_72));
  MUX2X1 g3498__5115(.A (can_tx_data_bus[31]), .B
       (can_tx_data_bus[23]), .S (uart_data_ready), .Z (n_71));
  MUX2X1 g3499__7482(.A (can_tx_data_bus[32]), .B
       (can_tx_data_bus[24]), .S (uart_data_ready), .Z (n_70));
  MUX2X1 g3500__4733(.A (can_tx_data_bus[33]), .B
       (can_tx_data_bus[25]), .S (uart_data_ready), .Z (n_69));
  MUX2X1 g3501__6161(.A (can_tx_data_bus[34]), .B
       (can_tx_data_bus[26]), .S (uart_data_ready), .Z (n_68));
  MUX2X1 g3502__9315(.A (can_tx_data_bus[35]), .B
       (can_tx_data_bus[27]), .S (uart_data_ready), .Z (n_67));
  MUX2X1 g3503__9945(.A (can_tx_data_bus[36]), .B
       (can_tx_data_bus[28]), .S (uart_data_ready), .Z (n_66));
  MUX2X1 g3504__2883(.A (can_tx_data_bus[37]), .B
       (can_tx_data_bus[29]), .S (uart_data_ready), .Z (n_65));
  MUX2X1 g3505__2346(.A (can_tx_data_bus[3]), .B (uart_rx_data_bus[3]),
       .S (uart_data_ready), .Z (n_64));
  MUX2X1 g3506__1666(.A (can_tx_data_bus[38]), .B
       (can_tx_data_bus[30]), .S (uart_data_ready), .Z (n_63));
  MUX2X1 g3507__7410(.A (can_tx_data_bus[39]), .B
       (can_tx_data_bus[31]), .S (uart_data_ready), .Z (n_62));
  MUX2X1 g3508__6417(.A (can_tx_data_bus[40]), .B
       (can_tx_data_bus[32]), .S (uart_data_ready), .Z (n_61));
  NOR2X1 g3509__5477(.A (n_12), .B (can_rx_inst_n_1019), .Z (n_60));
  AND2X1 g3510__2398(.A (n_13), .B (can_index[1]), .Z (n_100));
  NAND2X1 g3511__5107(.A (n_17), .B (n_14), .Z (n_99));
  XOR2X1 g3512__6260(.A (can_rx_inst_bit_count[0]), .B
       (can_rx_inst_bit_count[1]), .Z (n_59));
  MUX2X1 g3513__4319(.A (can_tx_data_bus[44]), .B
       (can_tx_data_bus[36]), .S (uart_data_ready), .Z (n_58));
  MUX2X1 g3514__8428(.A (can_tx_data_bus[45]), .B
       (can_tx_data_bus[37]), .S (uart_data_ready), .Z (n_57));
  MUX2X1 g3515__5526(.A (can_tx_data_bus[46]), .B
       (can_tx_data_bus[38]), .S (uart_data_ready), .Z (n_56));
  MUX2X1 g3516__6783(.A (can_tx_data_bus[47]), .B
       (can_tx_data_bus[39]), .S (uart_data_ready), .Z (n_55));
  MUX2X1 g3517__3680(.A (can_tx_data_bus[48]), .B
       (can_tx_data_bus[40]), .S (uart_data_ready), .Z (n_54));
  MUX2X1 g3518__1617(.A (can_tx_data_bus[49]), .B
       (can_tx_data_bus[41]), .S (uart_data_ready), .Z (n_53));
  MUX2X1 g3519__2802(.A (can_tx_data_bus[50]), .B
       (can_tx_data_bus[42]), .S (uart_data_ready), .Z (n_52));
  MUX2X1 g3520__1705(.A (can_tx_data_bus[51]), .B
       (can_tx_data_bus[43]), .S (uart_data_ready), .Z (n_51));
  MUX2X1 g3521__5122(.A (can_tx_data_bus[52]), .B
       (can_tx_data_bus[44]), .S (uart_data_ready), .Z (n_50));
  MUX2X1 g3522__8246(.A (can_tx_data_bus[53]), .B
       (can_tx_data_bus[45]), .S (uart_data_ready), .Z (n_49));
  MUX2X1 g3523__7098(.A (can_tx_data_bus[54]), .B
       (can_tx_data_bus[46]), .S (uart_data_ready), .Z (n_48));
  MUX2X1 g3524__6131(.A (can_tx_data_bus[55]), .B
       (can_tx_data_bus[47]), .S (uart_data_ready), .Z (n_47));
  MUX2X1 g3525__1881(.A (can_tx_data_bus[56]), .B
       (can_tx_data_bus[48]), .S (uart_data_ready), .Z (n_46));
  MUX2X1 g3526__5115(.A (can_tx_data_bus[57]), .B
       (can_tx_data_bus[49]), .S (uart_data_ready), .Z (n_45));
  MUX2X1 g3527__7482(.A (can_tx_data_bus[58]), .B
       (can_tx_data_bus[50]), .S (uart_data_ready), .Z (n_44));
  MUX2X1 g3528__4733(.A (can_tx_data_bus[59]), .B
       (can_tx_data_bus[51]), .S (uart_data_ready), .Z (n_43));
  MUX2X1 g3529__6161(.A (can_tx_data_bus[60]), .B
       (can_tx_data_bus[52]), .S (uart_data_ready), .Z (n_42));
  MUX2X1 g3530__9315(.A (can_tx_data_bus[62]), .B
       (can_tx_data_bus[54]), .S (uart_data_ready), .Z (n_41));
  MUX2X1 g3531__9945(.A (can_tx_data_bus[63]), .B
       (can_tx_data_bus[55]), .S (uart_data_ready), .Z (n_40));
  MUX2X1 g3532__2883(.A (can_tx_data_bus[61]), .B
       (can_tx_data_bus[53]), .S (uart_data_ready), .Z (n_39));
  MUX2X1 g3533__2346(.A (can_tx_data_bus[0]), .B (uart_rx_data_bus[0]),
       .S (uart_data_ready), .Z (n_38));
  MUX2X1 g3534__1666(.A (can_tx_data_bus[1]), .B (uart_rx_data_bus[1]),
       .S (uart_data_ready), .Z (n_37));
  MUX2X1 g3535__7410(.A (can_tx_data_bus[2]), .B (uart_rx_data_bus[2]),
       .S (uart_data_ready), .Z (n_36));
  MUX2X1 g3536__6417(.A (can_tx_data_bus[4]), .B (uart_rx_data_bus[4]),
       .S (uart_data_ready), .Z (n_35));
  MUX2X1 g3537__5477(.A (can_tx_data_bus[5]), .B (uart_rx_data_bus[5]),
       .S (uart_data_ready), .Z (n_34));
  MUX2X1 g3538__2398(.A (can_tx_data_bus[6]), .B (uart_rx_data_bus[6]),
       .S (uart_data_ready), .Z (n_33));
  MUX2X1 g3539__5107(.A (can_tx_data_bus[7]), .B (uart_rx_data_bus[7]),
       .S (uart_data_ready), .Z (n_32));
  MUX2X1 g3540__6260(.A (can_tx_data_bus[8]), .B (can_tx_data_bus[0]),
       .S (uart_data_ready), .Z (n_31));
  MUX2X1 g3541__4319(.A (can_tx_data_bus[9]), .B (can_tx_data_bus[1]),
       .S (uart_data_ready), .Z (n_30));
  MUX2X1 g3542__8428(.A (uart_tx_data_Bus[0]), .B (Can_rx_data_Bus[0]),
       .S (can_data_ready), .Z (n_29));
  MUX2X1 g3543__5526(.A (uart_tx_data_Bus[1]), .B (Can_rx_data_Bus[1]),
       .S (can_data_ready), .Z (n_28));
  MUX2X1 g3544__6783(.A (uart_tx_data_Bus[2]), .B (Can_rx_data_Bus[2]),
       .S (can_data_ready), .Z (n_27));
  MUX2X1 g3545__3680(.A (uart_tx_data_Bus[7]), .B (Can_rx_data_Bus[7]),
       .S (can_data_ready), .Z (n_26));
  MUX2X1 g3546__1617(.A (uart_tx_data_Bus[3]), .B (Can_rx_data_Bus[3]),
       .S (can_data_ready), .Z (n_25));
  MUX2X1 g3547__2802(.A (uart_tx_data_Bus[4]), .B (Can_rx_data_Bus[4]),
       .S (can_data_ready), .Z (n_24));
  MUX2X1 g3548__1705(.A (uart_tx_data_Bus[5]), .B (Can_rx_data_Bus[5]),
       .S (can_data_ready), .Z (n_23));
  MUX2X1 g3549__5122(.A (uart_tx_data_Bus[6]), .B (Can_rx_data_Bus[6]),
       .S (can_data_ready), .Z (n_22));
  XOR2X1 g3550__8246(.A (can_rx_inst_bit_count[4]), .B
       (can_rx_inst_n_1019), .Z (n_21));
  XOR2X1 g3551__7098(.A (can_rx_inst_bit_count[5]), .B (n_241), .Z
       (n_20));
  XOR2X1 g3552__6131(.A (can_rx_inst_bit_count[2]), .B (n_251), .Z
       (n_19));
  MUX2X1 g3553__1881(.A (can_tx_data_bus[43]), .B
       (can_tx_data_bus[35]), .S (uart_data_ready), .Z (n_18));
  NAND2X1 g3555__5115(.A (n_243), .B (n_5), .Z (n_17));
  NOR2X1 g3556__7482(.A (n_7), .B (n_251), .Z (n_16));
  INVX2 g3560(.A (n_14), .Z (n_15));
  NAND2X1 g3561__4733(.A (can_rx_inst_bit_count[4]), .B
       (can_rx_inst_bit_count[5]), .Z (n_12));
  AND2X1 g3562__6161(.A (Load_frame_datareg), .B (uart_data_ready), .Z
       (n_11));
  NOR2X1 g3563__9315(.A (uart_data_ready), .B (can_index[0]), .Z
       (n_10));
  NAND2X1 g3564__9945(.A (n_243), .B (can_data_ready), .Z (n_9));
  NAND2X1 g3565__2883(.A (can_rx_inst_state[1]), .B
       (can_rx_inst_state[2]), .Z (n_14));
  AND2X1 g3566__2346(.A (can_index[0]), .B (uart_data_ready), .Z
       (n_13));
  INVX2 g3581(.A (can_rx_inst_bit_count[2]), .Z (n_7));
  NAND2X1 g2115__3590(.A (n_194), .B (n_193), .Z (n_250));
  NAND2X1 g2(.A (can_rx_inst_bit_count[0]), .B
       (can_rx_inst_bit_count[1]), .Z (n_251));
endmodule

