# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.15-s080_1 on Wed Dec 04 21:39:56 MST 2024

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design bridge_soc_top

create_clock -name "clock" -period 2.0 -waveform {0.0 1.0} [get_ports clock]
group_path -weight 1.000000 -name C2C -from [list \
  [get_cells {soc_Can_ID_Bus_reg[0]}]  \
  [get_cells soc_Load_XMT_datareg_reg]  \
  [get_cells soc_Load_frame_datareg_reg]  \
  [get_cells {soc_can_index_reg[0]}]  \
  [get_cells {soc_can_index_reg[1]}]  \
  [get_cells {soc_can_index_reg[2]}]  \
  [get_cells soc_can_rx_inst_Can_data_ready_reg]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[0]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[1]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[2]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[3]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[4]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[5]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[6]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[7]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[0]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[1]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[2]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[3]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[4]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[5]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[6]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[60]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[61]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[62]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[63]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[64]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[65]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[66]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[67]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[68]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[69]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[70]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[71]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[72]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[73]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[74]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[75]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[76]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[77]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[78]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[79]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[80]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[81]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[82]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[83]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[84]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[85]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[86]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[87]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[88]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[89]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[90]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[91]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[92]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[93]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[94]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[95]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[96]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[97]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[98]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[99]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[100]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[101]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[102]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[103]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[104]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[105]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[106]}]  \
  [get_cells {soc_can_rx_inst_state_reg[1]}]  \
  [get_cells {soc_can_rx_inst_state_reg[2]}]  \
  [get_cells {soc_can_tx_data_bus_reg[0]}]  \
  [get_cells {soc_can_tx_data_bus_reg[1]}]  \
  [get_cells {soc_can_tx_data_bus_reg[2]}]  \
  [get_cells {soc_can_tx_data_bus_reg[3]}]  \
  [get_cells {soc_can_tx_data_bus_reg[4]}]  \
  [get_cells {soc_can_tx_data_bus_reg[5]}]  \
  [get_cells {soc_can_tx_data_bus_reg[6]}]  \
  [get_cells {soc_can_tx_data_bus_reg[7]}]  \
  [get_cells {soc_can_tx_data_bus_reg[8]}]  \
  [get_cells {soc_can_tx_data_bus_reg[9]}]  \
  [get_cells {soc_can_tx_data_bus_reg[10]}]  \
  [get_cells {soc_can_tx_data_bus_reg[11]}]  \
  [get_cells {soc_can_tx_data_bus_reg[12]}]  \
  [get_cells {soc_can_tx_data_bus_reg[13]}]  \
  [get_cells {soc_can_tx_data_bus_reg[14]}]  \
  [get_cells {soc_can_tx_data_bus_reg[15]}]  \
  [get_cells {soc_can_tx_data_bus_reg[16]}]  \
  [get_cells {soc_can_tx_data_bus_reg[17]}]  \
  [get_cells {soc_can_tx_data_bus_reg[18]}]  \
  [get_cells {soc_can_tx_data_bus_reg[19]}]  \
  [get_cells {soc_can_tx_data_bus_reg[20]}]  \
  [get_cells {soc_can_tx_data_bus_reg[21]}]  \
  [get_cells {soc_can_tx_data_bus_reg[22]}]  \
  [get_cells {soc_can_tx_data_bus_reg[23]}]  \
  [get_cells {soc_can_tx_data_bus_reg[24]}]  \
  [get_cells {soc_can_tx_data_bus_reg[25]}]  \
  [get_cells {soc_can_tx_data_bus_reg[26]}]  \
  [get_cells {soc_can_tx_data_bus_reg[27]}]  \
  [get_cells {soc_can_tx_data_bus_reg[28]}]  \
  [get_cells {soc_can_tx_data_bus_reg[29]}]  \
  [get_cells {soc_can_tx_data_bus_reg[30]}]  \
  [get_cells {soc_can_tx_data_bus_reg[31]}]  \
  [get_cells {soc_can_tx_data_bus_reg[32]}]  \
  [get_cells {soc_can_tx_data_bus_reg[33]}]  \
  [get_cells {soc_can_tx_data_bus_reg[34]}]  \
  [get_cells {soc_can_tx_data_bus_reg[35]}]  \
  [get_cells {soc_can_tx_data_bus_reg[36]}]  \
  [get_cells {soc_can_tx_data_bus_reg[37]}]  \
  [get_cells {soc_can_tx_data_bus_reg[38]}]  \
  [get_cells {soc_can_tx_data_bus_reg[39]}]  \
  [get_cells {soc_can_tx_data_bus_reg[40]}]  \
  [get_cells {soc_can_tx_data_bus_reg[41]}]  \
  [get_cells {soc_can_tx_data_bus_reg[42]}]  \
  [get_cells {soc_can_tx_data_bus_reg[43]}]  \
  [get_cells {soc_can_tx_data_bus_reg[44]}]  \
  [get_cells {soc_can_tx_data_bus_reg[45]}]  \
  [get_cells {soc_can_tx_data_bus_reg[46]}]  \
  [get_cells {soc_can_tx_data_bus_reg[47]}]  \
  [get_cells {soc_can_tx_data_bus_reg[48]}]  \
  [get_cells {soc_can_tx_data_bus_reg[49]}]  \
  [get_cells {soc_can_tx_data_bus_reg[50]}]  \
  [get_cells {soc_can_tx_data_bus_reg[51]}]  \
  [get_cells {soc_can_tx_data_bus_reg[52]}]  \
  [get_cells {soc_can_tx_data_bus_reg[53]}]  \
  [get_cells {soc_can_tx_data_bus_reg[54]}]  \
  [get_cells {soc_can_tx_data_bus_reg[55]}]  \
  [get_cells {soc_can_tx_data_bus_reg[56]}]  \
  [get_cells {soc_can_tx_data_bus_reg[57]}]  \
  [get_cells {soc_can_tx_data_bus_reg[58]}]  \
  [get_cells {soc_can_tx_data_bus_reg[59]}]  \
  [get_cells {soc_can_tx_data_bus_reg[60]}]  \
  [get_cells {soc_can_tx_data_bus_reg[61]}]  \
  [get_cells {soc_can_tx_data_bus_reg[62]}]  \
  [get_cells {soc_can_tx_data_bus_reg[63]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[0]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[1]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[2]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[3]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[4]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[5]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[6]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[7]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[8]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[9]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[10]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[11]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[12]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[13]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[14]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[15]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[16]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[17]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[18]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[19]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[20]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[21]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[22]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[23]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[24]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[25]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[26]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[27]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[28]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[29]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[30]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[31]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[32]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[33]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[34]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[35]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[36]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[37]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[38]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[39]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[40]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[41]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[42]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[43]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[44]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[45]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[46]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[47]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[48]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[49]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[50]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[51]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[52]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[53]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[54]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[55]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[56]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[57]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[58]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[59]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[60]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[61]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[62]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[63]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[64]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[65]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[66]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[67]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[68]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[69]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[70]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[71]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[72]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[73]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[74]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[75]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[76]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[77]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[78]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[79]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[80]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[81]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[82]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[83]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[84]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[85]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[86]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[87]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[88]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[89]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[90]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[91]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[92]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[93]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[94]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[95]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[96]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[97]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[98]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[99]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[100]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[101]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[102]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[103]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[104]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[105]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[106]}]  \
  [get_cells {soc_can_tx_inst_state_reg[0]}]  \
  [get_cells {soc_can_tx_inst_state_reg[1]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[0]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[1]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[2]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[3]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[4]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[5]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[6]}]  \
  [get_cells {soc_uart_rx_inst_bit_count_reg[0]}]  \
  [get_cells {soc_uart_rx_inst_bit_count_reg[1]}]  \
  [get_cells {soc_uart_rx_inst_bit_count_reg[2]}]  \
  [get_cells {soc_uart_rx_inst_bit_count_reg[3]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[1]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[2]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[3]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[4]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[5]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[6]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[7]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[8]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[9]}]  \
  [get_cells {soc_uart_rx_inst_state_reg[0]}]  \
  [get_cells {soc_uart_rx_inst_state_reg[1]}]  \
  [get_cells soc_uart_rx_inst_uart_data_ready_reg]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[0]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[1]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[2]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[3]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[4]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[5]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[6]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[7]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[0]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[1]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[2]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[3]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[4]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[5]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[6]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[7]}]  \
  [get_cells {soc_uart_tx_inst_Status_reg_reg[0]}]  \
  [get_cells {soc_uart_tx_inst_Status_reg_reg[1]}]  \
  [get_cells {soc_uart_tx_inst_Status_reg_reg[2]}]  \
  [get_cells {soc_uart_tx_inst_Status_reg_reg[3]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[0]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[1]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[2]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[3]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[4]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[5]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[6]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[7]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[8]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[9]}]  \
  [get_cells {soc_uart_tx_inst_state_reg[0]}]  \
  [get_cells {soc_uart_tx_inst_state_reg[1]}]  \
  [get_cells soc_Bridge_Can_out_reg]  \
  [get_cells soc_Bridge_Serial_out_reg] ] -to [list \
  [get_cells {soc_Can_ID_Bus_reg[0]}]  \
  [get_cells soc_Load_XMT_datareg_reg]  \
  [get_cells soc_Load_frame_datareg_reg]  \
  [get_cells {soc_can_index_reg[0]}]  \
  [get_cells {soc_can_index_reg[1]}]  \
  [get_cells {soc_can_index_reg[2]}]  \
  [get_cells soc_can_rx_inst_Can_data_ready_reg]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[0]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[1]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[2]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[3]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[4]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[5]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[6]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[7]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[0]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[1]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[2]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[3]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[4]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[5]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[6]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[60]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[61]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[62]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[63]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[64]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[65]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[66]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[67]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[68]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[69]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[70]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[71]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[72]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[73]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[74]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[75]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[76]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[77]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[78]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[79]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[80]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[81]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[82]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[83]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[84]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[85]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[86]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[87]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[88]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[89]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[90]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[91]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[92]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[93]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[94]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[95]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[96]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[97]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[98]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[99]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[100]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[101]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[102]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[103]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[104]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[105]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[106]}]  \
  [get_cells {soc_can_rx_inst_state_reg[1]}]  \
  [get_cells {soc_can_rx_inst_state_reg[2]}]  \
  [get_cells {soc_can_tx_data_bus_reg[0]}]  \
  [get_cells {soc_can_tx_data_bus_reg[1]}]  \
  [get_cells {soc_can_tx_data_bus_reg[2]}]  \
  [get_cells {soc_can_tx_data_bus_reg[3]}]  \
  [get_cells {soc_can_tx_data_bus_reg[4]}]  \
  [get_cells {soc_can_tx_data_bus_reg[5]}]  \
  [get_cells {soc_can_tx_data_bus_reg[6]}]  \
  [get_cells {soc_can_tx_data_bus_reg[7]}]  \
  [get_cells {soc_can_tx_data_bus_reg[8]}]  \
  [get_cells {soc_can_tx_data_bus_reg[9]}]  \
  [get_cells {soc_can_tx_data_bus_reg[10]}]  \
  [get_cells {soc_can_tx_data_bus_reg[11]}]  \
  [get_cells {soc_can_tx_data_bus_reg[12]}]  \
  [get_cells {soc_can_tx_data_bus_reg[13]}]  \
  [get_cells {soc_can_tx_data_bus_reg[14]}]  \
  [get_cells {soc_can_tx_data_bus_reg[15]}]  \
  [get_cells {soc_can_tx_data_bus_reg[16]}]  \
  [get_cells {soc_can_tx_data_bus_reg[17]}]  \
  [get_cells {soc_can_tx_data_bus_reg[18]}]  \
  [get_cells {soc_can_tx_data_bus_reg[19]}]  \
  [get_cells {soc_can_tx_data_bus_reg[20]}]  \
  [get_cells {soc_can_tx_data_bus_reg[21]}]  \
  [get_cells {soc_can_tx_data_bus_reg[22]}]  \
  [get_cells {soc_can_tx_data_bus_reg[23]}]  \
  [get_cells {soc_can_tx_data_bus_reg[24]}]  \
  [get_cells {soc_can_tx_data_bus_reg[25]}]  \
  [get_cells {soc_can_tx_data_bus_reg[26]}]  \
  [get_cells {soc_can_tx_data_bus_reg[27]}]  \
  [get_cells {soc_can_tx_data_bus_reg[28]}]  \
  [get_cells {soc_can_tx_data_bus_reg[29]}]  \
  [get_cells {soc_can_tx_data_bus_reg[30]}]  \
  [get_cells {soc_can_tx_data_bus_reg[31]}]  \
  [get_cells {soc_can_tx_data_bus_reg[32]}]  \
  [get_cells {soc_can_tx_data_bus_reg[33]}]  \
  [get_cells {soc_can_tx_data_bus_reg[34]}]  \
  [get_cells {soc_can_tx_data_bus_reg[35]}]  \
  [get_cells {soc_can_tx_data_bus_reg[36]}]  \
  [get_cells {soc_can_tx_data_bus_reg[37]}]  \
  [get_cells {soc_can_tx_data_bus_reg[38]}]  \
  [get_cells {soc_can_tx_data_bus_reg[39]}]  \
  [get_cells {soc_can_tx_data_bus_reg[40]}]  \
  [get_cells {soc_can_tx_data_bus_reg[41]}]  \
  [get_cells {soc_can_tx_data_bus_reg[42]}]  \
  [get_cells {soc_can_tx_data_bus_reg[43]}]  \
  [get_cells {soc_can_tx_data_bus_reg[44]}]  \
  [get_cells {soc_can_tx_data_bus_reg[45]}]  \
  [get_cells {soc_can_tx_data_bus_reg[46]}]  \
  [get_cells {soc_can_tx_data_bus_reg[47]}]  \
  [get_cells {soc_can_tx_data_bus_reg[48]}]  \
  [get_cells {soc_can_tx_data_bus_reg[49]}]  \
  [get_cells {soc_can_tx_data_bus_reg[50]}]  \
  [get_cells {soc_can_tx_data_bus_reg[51]}]  \
  [get_cells {soc_can_tx_data_bus_reg[52]}]  \
  [get_cells {soc_can_tx_data_bus_reg[53]}]  \
  [get_cells {soc_can_tx_data_bus_reg[54]}]  \
  [get_cells {soc_can_tx_data_bus_reg[55]}]  \
  [get_cells {soc_can_tx_data_bus_reg[56]}]  \
  [get_cells {soc_can_tx_data_bus_reg[57]}]  \
  [get_cells {soc_can_tx_data_bus_reg[58]}]  \
  [get_cells {soc_can_tx_data_bus_reg[59]}]  \
  [get_cells {soc_can_tx_data_bus_reg[60]}]  \
  [get_cells {soc_can_tx_data_bus_reg[61]}]  \
  [get_cells {soc_can_tx_data_bus_reg[62]}]  \
  [get_cells {soc_can_tx_data_bus_reg[63]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[0]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[1]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[2]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[3]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[4]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[5]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[6]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[7]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[8]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[9]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[10]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[11]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[12]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[13]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[14]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[15]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[16]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[17]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[18]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[19]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[20]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[21]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[22]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[23]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[24]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[25]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[26]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[27]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[28]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[29]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[30]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[31]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[32]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[33]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[34]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[35]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[36]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[37]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[38]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[39]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[40]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[41]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[42]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[43]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[44]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[45]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[46]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[47]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[48]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[49]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[50]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[51]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[52]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[53]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[54]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[55]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[56]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[57]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[58]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[59]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[60]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[61]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[62]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[63]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[64]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[65]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[66]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[67]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[68]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[69]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[70]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[71]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[72]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[73]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[74]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[75]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[76]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[77]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[78]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[79]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[80]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[81]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[82]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[83]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[84]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[85]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[86]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[87]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[88]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[89]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[90]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[91]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[92]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[93]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[94]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[95]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[96]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[97]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[98]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[99]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[100]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[101]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[102]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[103]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[104]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[105]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[106]}]  \
  [get_cells {soc_can_tx_inst_state_reg[0]}]  \
  [get_cells {soc_can_tx_inst_state_reg[1]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[0]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[1]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[2]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[3]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[4]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[5]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[6]}]  \
  [get_cells {soc_uart_rx_inst_bit_count_reg[0]}]  \
  [get_cells {soc_uart_rx_inst_bit_count_reg[1]}]  \
  [get_cells {soc_uart_rx_inst_bit_count_reg[2]}]  \
  [get_cells {soc_uart_rx_inst_bit_count_reg[3]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[1]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[2]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[3]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[4]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[5]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[6]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[7]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[8]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[9]}]  \
  [get_cells {soc_uart_rx_inst_state_reg[0]}]  \
  [get_cells {soc_uart_rx_inst_state_reg[1]}]  \
  [get_cells soc_uart_rx_inst_uart_data_ready_reg]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[0]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[1]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[2]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[3]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[4]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[5]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[6]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[7]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[0]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[1]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[2]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[3]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[4]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[5]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[6]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[7]}]  \
  [get_cells {soc_uart_tx_inst_Status_reg_reg[0]}]  \
  [get_cells {soc_uart_tx_inst_Status_reg_reg[1]}]  \
  [get_cells {soc_uart_tx_inst_Status_reg_reg[2]}]  \
  [get_cells {soc_uart_tx_inst_Status_reg_reg[3]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[0]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[1]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[2]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[3]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[4]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[5]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[6]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[7]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[8]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[9]}]  \
  [get_cells {soc_uart_tx_inst_state_reg[0]}]  \
  [get_cells {soc_uart_tx_inst_state_reg[1]}]  \
  [get_cells soc_Bridge_Can_out_reg]  \
  [get_cells soc_Bridge_Serial_out_reg] ]
group_path -weight 1.000000 -name C2O -from [list \
  [get_cells {soc_Can_ID_Bus_reg[0]}]  \
  [get_cells soc_Load_XMT_datareg_reg]  \
  [get_cells soc_Load_frame_datareg_reg]  \
  [get_cells {soc_can_index_reg[0]}]  \
  [get_cells {soc_can_index_reg[1]}]  \
  [get_cells {soc_can_index_reg[2]}]  \
  [get_cells soc_can_rx_inst_Can_data_ready_reg]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[0]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[1]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[2]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[3]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[4]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[5]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[6]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[7]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[0]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[1]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[2]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[3]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[4]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[5]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[6]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[60]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[61]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[62]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[63]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[64]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[65]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[66]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[67]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[68]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[69]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[70]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[71]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[72]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[73]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[74]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[75]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[76]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[77]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[78]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[79]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[80]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[81]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[82]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[83]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[84]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[85]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[86]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[87]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[88]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[89]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[90]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[91]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[92]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[93]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[94]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[95]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[96]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[97]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[98]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[99]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[100]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[101]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[102]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[103]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[104]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[105]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[106]}]  \
  [get_cells {soc_can_rx_inst_state_reg[1]}]  \
  [get_cells {soc_can_rx_inst_state_reg[2]}]  \
  [get_cells {soc_can_tx_data_bus_reg[0]}]  \
  [get_cells {soc_can_tx_data_bus_reg[1]}]  \
  [get_cells {soc_can_tx_data_bus_reg[2]}]  \
  [get_cells {soc_can_tx_data_bus_reg[3]}]  \
  [get_cells {soc_can_tx_data_bus_reg[4]}]  \
  [get_cells {soc_can_tx_data_bus_reg[5]}]  \
  [get_cells {soc_can_tx_data_bus_reg[6]}]  \
  [get_cells {soc_can_tx_data_bus_reg[7]}]  \
  [get_cells {soc_can_tx_data_bus_reg[8]}]  \
  [get_cells {soc_can_tx_data_bus_reg[9]}]  \
  [get_cells {soc_can_tx_data_bus_reg[10]}]  \
  [get_cells {soc_can_tx_data_bus_reg[11]}]  \
  [get_cells {soc_can_tx_data_bus_reg[12]}]  \
  [get_cells {soc_can_tx_data_bus_reg[13]}]  \
  [get_cells {soc_can_tx_data_bus_reg[14]}]  \
  [get_cells {soc_can_tx_data_bus_reg[15]}]  \
  [get_cells {soc_can_tx_data_bus_reg[16]}]  \
  [get_cells {soc_can_tx_data_bus_reg[17]}]  \
  [get_cells {soc_can_tx_data_bus_reg[18]}]  \
  [get_cells {soc_can_tx_data_bus_reg[19]}]  \
  [get_cells {soc_can_tx_data_bus_reg[20]}]  \
  [get_cells {soc_can_tx_data_bus_reg[21]}]  \
  [get_cells {soc_can_tx_data_bus_reg[22]}]  \
  [get_cells {soc_can_tx_data_bus_reg[23]}]  \
  [get_cells {soc_can_tx_data_bus_reg[24]}]  \
  [get_cells {soc_can_tx_data_bus_reg[25]}]  \
  [get_cells {soc_can_tx_data_bus_reg[26]}]  \
  [get_cells {soc_can_tx_data_bus_reg[27]}]  \
  [get_cells {soc_can_tx_data_bus_reg[28]}]  \
  [get_cells {soc_can_tx_data_bus_reg[29]}]  \
  [get_cells {soc_can_tx_data_bus_reg[30]}]  \
  [get_cells {soc_can_tx_data_bus_reg[31]}]  \
  [get_cells {soc_can_tx_data_bus_reg[32]}]  \
  [get_cells {soc_can_tx_data_bus_reg[33]}]  \
  [get_cells {soc_can_tx_data_bus_reg[34]}]  \
  [get_cells {soc_can_tx_data_bus_reg[35]}]  \
  [get_cells {soc_can_tx_data_bus_reg[36]}]  \
  [get_cells {soc_can_tx_data_bus_reg[37]}]  \
  [get_cells {soc_can_tx_data_bus_reg[38]}]  \
  [get_cells {soc_can_tx_data_bus_reg[39]}]  \
  [get_cells {soc_can_tx_data_bus_reg[40]}]  \
  [get_cells {soc_can_tx_data_bus_reg[41]}]  \
  [get_cells {soc_can_tx_data_bus_reg[42]}]  \
  [get_cells {soc_can_tx_data_bus_reg[43]}]  \
  [get_cells {soc_can_tx_data_bus_reg[44]}]  \
  [get_cells {soc_can_tx_data_bus_reg[45]}]  \
  [get_cells {soc_can_tx_data_bus_reg[46]}]  \
  [get_cells {soc_can_tx_data_bus_reg[47]}]  \
  [get_cells {soc_can_tx_data_bus_reg[48]}]  \
  [get_cells {soc_can_tx_data_bus_reg[49]}]  \
  [get_cells {soc_can_tx_data_bus_reg[50]}]  \
  [get_cells {soc_can_tx_data_bus_reg[51]}]  \
  [get_cells {soc_can_tx_data_bus_reg[52]}]  \
  [get_cells {soc_can_tx_data_bus_reg[53]}]  \
  [get_cells {soc_can_tx_data_bus_reg[54]}]  \
  [get_cells {soc_can_tx_data_bus_reg[55]}]  \
  [get_cells {soc_can_tx_data_bus_reg[56]}]  \
  [get_cells {soc_can_tx_data_bus_reg[57]}]  \
  [get_cells {soc_can_tx_data_bus_reg[58]}]  \
  [get_cells {soc_can_tx_data_bus_reg[59]}]  \
  [get_cells {soc_can_tx_data_bus_reg[60]}]  \
  [get_cells {soc_can_tx_data_bus_reg[61]}]  \
  [get_cells {soc_can_tx_data_bus_reg[62]}]  \
  [get_cells {soc_can_tx_data_bus_reg[63]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[0]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[1]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[2]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[3]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[4]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[5]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[6]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[7]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[8]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[9]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[10]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[11]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[12]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[13]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[14]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[15]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[16]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[17]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[18]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[19]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[20]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[21]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[22]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[23]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[24]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[25]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[26]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[27]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[28]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[29]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[30]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[31]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[32]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[33]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[34]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[35]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[36]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[37]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[38]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[39]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[40]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[41]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[42]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[43]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[44]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[45]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[46]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[47]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[48]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[49]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[50]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[51]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[52]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[53]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[54]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[55]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[56]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[57]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[58]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[59]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[60]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[61]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[62]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[63]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[64]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[65]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[66]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[67]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[68]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[69]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[70]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[71]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[72]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[73]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[74]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[75]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[76]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[77]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[78]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[79]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[80]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[81]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[82]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[83]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[84]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[85]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[86]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[87]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[88]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[89]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[90]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[91]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[92]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[93]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[94]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[95]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[96]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[97]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[98]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[99]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[100]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[101]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[102]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[103]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[104]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[105]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[106]}]  \
  [get_cells {soc_can_tx_inst_state_reg[0]}]  \
  [get_cells {soc_can_tx_inst_state_reg[1]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[0]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[1]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[2]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[3]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[4]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[5]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[6]}]  \
  [get_cells {soc_uart_rx_inst_bit_count_reg[0]}]  \
  [get_cells {soc_uart_rx_inst_bit_count_reg[1]}]  \
  [get_cells {soc_uart_rx_inst_bit_count_reg[2]}]  \
  [get_cells {soc_uart_rx_inst_bit_count_reg[3]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[1]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[2]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[3]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[4]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[5]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[6]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[7]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[8]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[9]}]  \
  [get_cells {soc_uart_rx_inst_state_reg[0]}]  \
  [get_cells {soc_uart_rx_inst_state_reg[1]}]  \
  [get_cells soc_uart_rx_inst_uart_data_ready_reg]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[0]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[1]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[2]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[3]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[4]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[5]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[6]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[7]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[0]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[1]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[2]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[3]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[4]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[5]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[6]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[7]}]  \
  [get_cells {soc_uart_tx_inst_Status_reg_reg[0]}]  \
  [get_cells {soc_uart_tx_inst_Status_reg_reg[1]}]  \
  [get_cells {soc_uart_tx_inst_Status_reg_reg[2]}]  \
  [get_cells {soc_uart_tx_inst_Status_reg_reg[3]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[0]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[1]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[2]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[3]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[4]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[5]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[6]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[7]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[8]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[9]}]  \
  [get_cells {soc_uart_tx_inst_state_reg[0]}]  \
  [get_cells {soc_uart_tx_inst_state_reg[1]}]  \
  [get_cells soc_Bridge_Can_out_reg]  \
  [get_cells soc_Bridge_Serial_out_reg] ] -to [list \
  [get_ports Bridge_Serial_out]  \
  [get_ports Bridge_Can_out] ]
group_path -weight 1.000000 -name I2C -from [list \
  [get_ports clock]  \
  [get_ports reset]  \
  [get_ports Serial_in]  \
  [get_ports Can_rx]  \
  [get_ports R_byte]  \
  [get_ports T_byte] ] -to [list \
  [get_cells {soc_Can_ID_Bus_reg[0]}]  \
  [get_cells soc_Load_XMT_datareg_reg]  \
  [get_cells soc_Load_frame_datareg_reg]  \
  [get_cells {soc_can_index_reg[0]}]  \
  [get_cells {soc_can_index_reg[1]}]  \
  [get_cells {soc_can_index_reg[2]}]  \
  [get_cells soc_can_rx_inst_Can_data_ready_reg]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[0]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[1]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[2]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[3]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[4]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[5]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[6]}]  \
  [get_cells {soc_can_rx_inst_Can_rx_data_Bus_reg[7]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[0]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[1]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[2]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[3]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[4]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[5]}]  \
  [get_cells {soc_can_rx_inst_bit_count_reg[6]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[60]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[61]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[62]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[63]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[64]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[65]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[66]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[67]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[68]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[69]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[70]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[71]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[72]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[73]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[74]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[75]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[76]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[77]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[78]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[79]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[80]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[81]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[82]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[83]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[84]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[85]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[86]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[87]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[88]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[89]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[90]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[91]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[92]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[93]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[94]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[95]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[96]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[97]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[98]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[99]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[100]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[101]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[102]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[103]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[104]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[105]}]  \
  [get_cells {soc_can_rx_inst_shift_reg_reg[106]}]  \
  [get_cells {soc_can_rx_inst_state_reg[1]}]  \
  [get_cells {soc_can_rx_inst_state_reg[2]}]  \
  [get_cells {soc_can_tx_data_bus_reg[0]}]  \
  [get_cells {soc_can_tx_data_bus_reg[1]}]  \
  [get_cells {soc_can_tx_data_bus_reg[2]}]  \
  [get_cells {soc_can_tx_data_bus_reg[3]}]  \
  [get_cells {soc_can_tx_data_bus_reg[4]}]  \
  [get_cells {soc_can_tx_data_bus_reg[5]}]  \
  [get_cells {soc_can_tx_data_bus_reg[6]}]  \
  [get_cells {soc_can_tx_data_bus_reg[7]}]  \
  [get_cells {soc_can_tx_data_bus_reg[8]}]  \
  [get_cells {soc_can_tx_data_bus_reg[9]}]  \
  [get_cells {soc_can_tx_data_bus_reg[10]}]  \
  [get_cells {soc_can_tx_data_bus_reg[11]}]  \
  [get_cells {soc_can_tx_data_bus_reg[12]}]  \
  [get_cells {soc_can_tx_data_bus_reg[13]}]  \
  [get_cells {soc_can_tx_data_bus_reg[14]}]  \
  [get_cells {soc_can_tx_data_bus_reg[15]}]  \
  [get_cells {soc_can_tx_data_bus_reg[16]}]  \
  [get_cells {soc_can_tx_data_bus_reg[17]}]  \
  [get_cells {soc_can_tx_data_bus_reg[18]}]  \
  [get_cells {soc_can_tx_data_bus_reg[19]}]  \
  [get_cells {soc_can_tx_data_bus_reg[20]}]  \
  [get_cells {soc_can_tx_data_bus_reg[21]}]  \
  [get_cells {soc_can_tx_data_bus_reg[22]}]  \
  [get_cells {soc_can_tx_data_bus_reg[23]}]  \
  [get_cells {soc_can_tx_data_bus_reg[24]}]  \
  [get_cells {soc_can_tx_data_bus_reg[25]}]  \
  [get_cells {soc_can_tx_data_bus_reg[26]}]  \
  [get_cells {soc_can_tx_data_bus_reg[27]}]  \
  [get_cells {soc_can_tx_data_bus_reg[28]}]  \
  [get_cells {soc_can_tx_data_bus_reg[29]}]  \
  [get_cells {soc_can_tx_data_bus_reg[30]}]  \
  [get_cells {soc_can_tx_data_bus_reg[31]}]  \
  [get_cells {soc_can_tx_data_bus_reg[32]}]  \
  [get_cells {soc_can_tx_data_bus_reg[33]}]  \
  [get_cells {soc_can_tx_data_bus_reg[34]}]  \
  [get_cells {soc_can_tx_data_bus_reg[35]}]  \
  [get_cells {soc_can_tx_data_bus_reg[36]}]  \
  [get_cells {soc_can_tx_data_bus_reg[37]}]  \
  [get_cells {soc_can_tx_data_bus_reg[38]}]  \
  [get_cells {soc_can_tx_data_bus_reg[39]}]  \
  [get_cells {soc_can_tx_data_bus_reg[40]}]  \
  [get_cells {soc_can_tx_data_bus_reg[41]}]  \
  [get_cells {soc_can_tx_data_bus_reg[42]}]  \
  [get_cells {soc_can_tx_data_bus_reg[43]}]  \
  [get_cells {soc_can_tx_data_bus_reg[44]}]  \
  [get_cells {soc_can_tx_data_bus_reg[45]}]  \
  [get_cells {soc_can_tx_data_bus_reg[46]}]  \
  [get_cells {soc_can_tx_data_bus_reg[47]}]  \
  [get_cells {soc_can_tx_data_bus_reg[48]}]  \
  [get_cells {soc_can_tx_data_bus_reg[49]}]  \
  [get_cells {soc_can_tx_data_bus_reg[50]}]  \
  [get_cells {soc_can_tx_data_bus_reg[51]}]  \
  [get_cells {soc_can_tx_data_bus_reg[52]}]  \
  [get_cells {soc_can_tx_data_bus_reg[53]}]  \
  [get_cells {soc_can_tx_data_bus_reg[54]}]  \
  [get_cells {soc_can_tx_data_bus_reg[55]}]  \
  [get_cells {soc_can_tx_data_bus_reg[56]}]  \
  [get_cells {soc_can_tx_data_bus_reg[57]}]  \
  [get_cells {soc_can_tx_data_bus_reg[58]}]  \
  [get_cells {soc_can_tx_data_bus_reg[59]}]  \
  [get_cells {soc_can_tx_data_bus_reg[60]}]  \
  [get_cells {soc_can_tx_data_bus_reg[61]}]  \
  [get_cells {soc_can_tx_data_bus_reg[62]}]  \
  [get_cells {soc_can_tx_data_bus_reg[63]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[0]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[1]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[2]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[3]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[4]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[5]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[6]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[7]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[8]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[9]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[10]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[11]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[12]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[13]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[14]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[15]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[16]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[17]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[18]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[19]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[20]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[21]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[22]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[23]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[24]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[25]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[26]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[27]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[28]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[29]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[30]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[31]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[32]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[33]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[34]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[35]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[36]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[37]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[38]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[39]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[40]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[41]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[42]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[43]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[44]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[45]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[46]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[47]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[48]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[49]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[50]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[51]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[52]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[53]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[54]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[55]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[56]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[57]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[58]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[59]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[60]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[61]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[62]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[63]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[64]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[65]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[66]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[67]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[68]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[69]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[70]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[71]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[72]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[73]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[74]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[75]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[76]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[77]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[78]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[79]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[80]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[81]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[82]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[83]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[84]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[85]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[86]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[87]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[88]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[89]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[90]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[91]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[92]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[93]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[94]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[95]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[96]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[97]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[98]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[99]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[100]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[101]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[102]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[103]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[104]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[105]}]  \
  [get_cells {soc_can_tx_inst_shift_reg_reg[106]}]  \
  [get_cells {soc_can_tx_inst_state_reg[0]}]  \
  [get_cells {soc_can_tx_inst_state_reg[1]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[0]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[1]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[2]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[3]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[4]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[5]}]  \
  [get_cells {soc_can_tx_inst_status_reg_reg[6]}]  \
  [get_cells {soc_uart_rx_inst_bit_count_reg[0]}]  \
  [get_cells {soc_uart_rx_inst_bit_count_reg[1]}]  \
  [get_cells {soc_uart_rx_inst_bit_count_reg[2]}]  \
  [get_cells {soc_uart_rx_inst_bit_count_reg[3]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[1]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[2]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[3]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[4]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[5]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[6]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[7]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[8]}]  \
  [get_cells {soc_uart_rx_inst_shift_reg_reg[9]}]  \
  [get_cells {soc_uart_rx_inst_state_reg[0]}]  \
  [get_cells {soc_uart_rx_inst_state_reg[1]}]  \
  [get_cells soc_uart_rx_inst_uart_data_ready_reg]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[0]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[1]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[2]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[3]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[4]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[5]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[6]}]  \
  [get_cells {soc_uart_rx_inst_uart_rx_data_bus_reg[7]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[0]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[1]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[2]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[3]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[4]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[5]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[6]}]  \
  [get_cells {soc_uart_tx_data_Bus_reg[7]}]  \
  [get_cells {soc_uart_tx_inst_Status_reg_reg[0]}]  \
  [get_cells {soc_uart_tx_inst_Status_reg_reg[1]}]  \
  [get_cells {soc_uart_tx_inst_Status_reg_reg[2]}]  \
  [get_cells {soc_uart_tx_inst_Status_reg_reg[3]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[0]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[1]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[2]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[3]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[4]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[5]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[6]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[7]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[8]}]  \
  [get_cells {soc_uart_tx_inst_shift_reg_reg[9]}]  \
  [get_cells {soc_uart_tx_inst_state_reg[0]}]  \
  [get_cells {soc_uart_tx_inst_state_reg[1]}]  \
  [get_cells soc_Bridge_Can_out_reg]  \
  [get_cells soc_Bridge_Serial_out_reg] ]
group_path -weight 1.000000 -name I2O -from [list \
  [get_ports clock]  \
  [get_ports reset]  \
  [get_ports Serial_in]  \
  [get_ports Can_rx]  \
  [get_ports R_byte]  \
  [get_ports T_byte] ] -to [list \
  [get_ports Bridge_Serial_out]  \
  [get_ports Bridge_Can_out] ]
set_clock_gating_check -setup 0.0 
