###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID lnissrv4)
#  Generated on:      Thu Dec  5 21:39:48 2024
#  Design:            bridge_soc_top
#  Command:           create_ccopt_clock_tree_spec -file ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are on the boundary of the STA clock network
# These pins are ignore skew pins
set_ccopt_property sink_type -pin clk_pad/pad ignore
set_ccopt_property sink_type_reasons -pin clk_pad/pad no_sdc_clock

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clock true

# Clocks present at pin clock
#   clock (period 2.000ns) in timing_config constraint([SDC/bridge_soc_top_m.sdc])
create_ccopt_clock_tree -name clock -source clock -no_skew_group
# Clock period setting for source pin of clock
set_ccopt_property clock_period -pin clock 2

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clock in timing_config:constraint (sdc SDC/bridge_soc_top_m.sdc)
create_ccopt_skew_group -name clock/constraint -sources clock -auto_sinks
set_ccopt_property include_source_latency -skew_group clock/constraint true
set_ccopt_property extracted_from_clock_name -skew_group clock/constraint clock
set_ccopt_property extracted_from_constraint_mode_name -skew_group clock/constraint constraint
set_ccopt_property extracted_from_delay_corners -skew_group clock/constraint {wc bc}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

