
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Dec  4 2024 13:32:51 MST (Dec  4 2024 20:32:51 UTC)

// Verification Directory fv/uart_can_bridge 

module uart_can_bridge(clock, reset, Serial_in, Can_rx, Bridge_Can_out,
     Bridge_Serial_out, R_byte, T_byte);
  input clock, reset, Serial_in, Can_rx, R_byte, T_byte;
  output Bridge_Can_out, Bridge_Serial_out;
  wire clock, reset, Serial_in, Can_rx, R_byte, T_byte;
  wire Bridge_Can_out, Bridge_Serial_out;
  wire [11:0] Can_ID_Bus;
  wire [106:0] can_tx_inst_shift_reg;
  wire [2:0] can_tx_inst_state;
  wire [2:0] can_index;
  wire [63:0] can_tx_data_bus;
  wire [6:0] can_tx_inst_status_reg;
  wire [3:0] uart_rx_inst_bit_count;
  wire [9:0] uart_rx_inst_shift_reg;
  wire [2:0] uart_rx_inst_state;
  wire [7:0] uart_rx_data_bus;
  wire Can_out, Load_frame_datareg, Serial_out, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_7, n_8, n_9, n_10, n_11, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_224;
  wire n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_233, n_234, n_235, n_236, n_237, n_238, n_239, n_240;
  wire n_241, n_242, n_243, n_244, n_245, n_246, n_247, n_248;
  wire n_249, n_250, n_252, n_253, n_254, n_255, n_256, n_257;
  wire n_258, n_259, n_260, n_261, n_262, n_263, n_264, n_265;
  wire n_266, n_267, n_268, n_269, n_270, n_271, n_272, n_273;
  wire n_274, n_275, n_276, n_277, n_278, n_279, n_280, n_281;
  wire n_282, n_283, n_284, n_285, n_286, n_287, n_288, n_289;
  wire n_290, n_291, n_292, n_293, n_294, n_295, n_296, n_297;
  wire n_298, n_299, n_300, n_301, n_302, n_303, n_304, n_305;
  wire n_306, n_307, n_308, n_309, n_310, n_311, n_312, n_313;
  wire n_314, n_315, n_316, n_317, n_318, n_319, n_320, n_321;
  wire n_322, n_323, n_324, n_325, n_326, n_327, n_328, n_329;
  wire n_330, n_331, n_332, n_333, n_334, n_335, n_336, n_337;
  wire n_338, n_339, n_340, n_341, n_342, n_343, n_344, n_345;
  wire n_346, n_347, n_348, n_349, n_350, n_351, n_352, n_353;
  wire n_354, n_355, n_356, n_357, n_358, n_359, n_360, n_361;
  wire n_362, n_363, n_364, n_365, n_366, n_367, n_368, n_369;
  wire n_370, n_371, n_372, n_373, n_374, n_375, n_376, n_377;
  wire n_378, n_379, n_381, n_382, n_383, n_384, n_385, n_386;
  wire n_387, n_388, n_389, n_390, n_391, n_392, n_393, n_394;
  wire n_395, n_396, n_397, n_398, n_399, n_400, n_401, n_402;
  wire n_403, n_404, n_405, n_406, n_407, n_408, n_409, n_410;
  wire n_411, n_412, n_413, n_414, n_415, n_416, n_417, n_418;
  wire n_419, n_420, n_421, n_422, n_423, n_424, n_425, n_426;
  wire n_427, n_428, n_429, n_430, n_431, n_432, n_433, n_434;
  wire n_435, n_436, n_437, n_438, n_439, n_440, n_441, n_442;
  wire n_443, n_444, n_445, n_446, n_447, n_448, n_449, n_450;
  wire n_451, n_452, n_453, n_454, n_455, n_456, n_457, n_458;
  wire n_459, n_460, n_461, n_462, n_463, n_464, n_465, n_466;
  wire n_467, n_468, n_469, n_470, n_471, n_472, n_473, n_474;
  wire n_475, n_476, n_477, n_478, n_479, n_480, n_481, n_482;
  wire n_483, n_484, n_485, n_486, n_487, n_488, n_489, n_490;
  wire n_491, n_492, n_493, n_494, n_495, n_496, n_497, n_498;
  wire n_499, n_500, n_501, n_502, n_503, n_504, n_505, n_506;
  wire n_507, n_508, n_509, n_510, n_511, n_512, n_513, n_514;
  wire n_515, n_516, n_517, n_518, n_519, n_520, n_521, n_522;
  wire n_523, n_524, n_525, n_526, n_527, n_528, n_529, n_530;
  wire n_531, n_532, n_533, n_534, n_535, n_536, n_537, n_538;
  wire n_539, n_540, n_541, n_542, n_543, n_544, n_545, n_546;
  wire n_547, n_548, n_549, n_550, n_551, n_552, n_553, n_554;
  wire n_555, n_556, n_557, n_558, n_559, n_560, n_561, n_562;
  wire n_563, n_564, n_565, n_566, n_567, n_568, n_569, n_570;
  wire n_571, n_572, n_573, n_574, n_575, n_576, n_577, n_578;
  wire n_579, n_580, n_581, n_582, n_583, n_584, n_585, n_586;
  wire n_587, n_590, n_592, n_593, n_601, n_602, uart_data_ready;
  assign Serial_out = 1'b1;
  assign Can_out = 1'b1;
  INVX2 g4379(.A (Can_ID_Bus[0]), .Z (n_590));
  DFFQSRX1 Bridge_Can_out_reg(.SETB (1'b1), .RESETB (n_13), .CLK
       (clock), .D (Can_out), .Q (Bridge_Can_out));
  DFFQSRX1 Bridge_Serial_out_reg(.SETB (1'b1), .RESETB (n_13), .CLK
       (clock), .D (Serial_out), .Q (Bridge_Serial_out));
  INVX2 g4380(.A (reset), .Z (n_13));
  NAND3X1 g4407__2398(.A (n_587), .B (n_593), .C (n_592), .Z (Can_out));
  NOR2X1 g4408__5107(.A (can_tx_inst_shift_reg[0]), .B (n_586), .Z
       (n_587));
  NAND2X1 g4409__6260(.A (can_tx_inst_state[0]), .B (n_590), .Z
       (n_592));
  NOR2X1 g4410__4319(.A (can_tx_inst_state[1]), .B
       (can_tx_inst_state[0]), .Z (n_586));
  NAND2X1 g4411__8428(.A (can_tx_inst_state[0]), .B
       (can_tx_inst_state[1]), .Z (n_593));
  DFFQSRX1 \Can_ID_Bus_reg[0] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_458), .Q (Can_ID_Bus[0]));
  DFFQSRX1 Load_frame_datareg_reg(.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_355), .Q (Load_frame_datareg));
  DFFQSRX1 \can_index_reg[0] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_125), .Q (can_index[0]));
  DFFQSRX1 \can_index_reg[1] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_244), .Q (can_index[1]));
  DFFQSRX1 \can_index_reg[2] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_282), .Q (can_index[2]));
  DFFQSRX1 \can_tx_data_bus_reg[0] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_120), .Q (can_tx_data_bus[0]));
  DFFQSRX1 \can_tx_data_bus_reg[1] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_104), .Q (can_tx_data_bus[1]));
  DFFQSRX1 \can_tx_data_bus_reg[2] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_85), .Q (can_tx_data_bus[2]));
  DFFQSRX1 \can_tx_data_bus_reg[3] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_71), .Q (can_tx_data_bus[3]));
  DFFQSRX1 \can_tx_data_bus_reg[4] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_74), .Q (can_tx_data_bus[4]));
  DFFQSRX1 \can_tx_data_bus_reg[5] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_122), .Q (can_tx_data_bus[5]));
  DFFQSRX1 \can_tx_data_bus_reg[6] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_118), .Q (can_tx_data_bus[6]));
  DFFQSRX1 \can_tx_data_bus_reg[7] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_105), .Q (can_tx_data_bus[7]));
  DFFQSRX1 \can_tx_data_bus_reg[8] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_100), .Q (can_tx_data_bus[8]));
  DFFQSRX1 \can_tx_data_bus_reg[9] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_94), .Q (can_tx_data_bus[9]));
  DFFQSRX1 \can_tx_data_bus_reg[10] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_84), .Q (can_tx_data_bus[10]));
  DFFQSRX1 \can_tx_data_bus_reg[11] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_80), .Q (can_tx_data_bus[11]));
  DFFQSRX1 \can_tx_data_bus_reg[12] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_112), .Q (can_tx_data_bus[12]));
  DFFQSRX1 \can_tx_data_bus_reg[13] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_66), .Q (can_tx_data_bus[13]));
  DFFQSRX1 \can_tx_data_bus_reg[14] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_67), .Q (can_tx_data_bus[14]));
  DFFQSRX1 \can_tx_data_bus_reg[15] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_63), .Q (can_tx_data_bus[15]));
  DFFQSRX1 \can_tx_data_bus_reg[16] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_76), .Q (can_tx_data_bus[16]));
  DFFQSRX1 \can_tx_data_bus_reg[17] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_109), .Q (can_tx_data_bus[17]));
  DFFQSRX1 \can_tx_data_bus_reg[18] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_123), .Q (can_tx_data_bus[18]));
  DFFQSRX1 \can_tx_data_bus_reg[19] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_81), .Q (can_tx_data_bus[19]));
  DFFQSRX1 \can_tx_data_bus_reg[20] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_82), .Q (can_tx_data_bus[20]));
  DFFQSRX1 \can_tx_data_bus_reg[21] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_115), .Q (can_tx_data_bus[21]));
  DFFQSRX1 \can_tx_data_bus_reg[22] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_110), .Q (can_tx_data_bus[22]));
  DFFQSRX1 \can_tx_data_bus_reg[23] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_107), .Q (can_tx_data_bus[23]));
  DFFQSRX1 \can_tx_data_bus_reg[24] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_102), .Q (can_tx_data_bus[24]));
  DFFQSRX1 \can_tx_data_bus_reg[25] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_98), .Q (can_tx_data_bus[25]));
  DFFQSRX1 \can_tx_data_bus_reg[26] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_93), .Q (can_tx_data_bus[26]));
  DFFQSRX1 \can_tx_data_bus_reg[27] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_90), .Q (can_tx_data_bus[27]));
  DFFQSRX1 \can_tx_data_bus_reg[28] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_114), .Q (can_tx_data_bus[28]));
  DFFQSRX1 \can_tx_data_bus_reg[29] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_83), .Q (can_tx_data_bus[29]));
  DFFQSRX1 \can_tx_data_bus_reg[30] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_79), .Q (can_tx_data_bus[30]));
  DFFQSRX1 \can_tx_data_bus_reg[31] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_78), .Q (can_tx_data_bus[31]));
  DFFQSRX1 \can_tx_data_bus_reg[32] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_86), .Q (can_tx_data_bus[32]));
  DFFQSRX1 \can_tx_data_bus_reg[33] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_75), .Q (can_tx_data_bus[33]));
  DFFQSRX1 \can_tx_data_bus_reg[34] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_70), .Q (can_tx_data_bus[34]));
  DFFQSRX1 \can_tx_data_bus_reg[35] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_68), .Q (can_tx_data_bus[35]));
  DFFQSRX1 \can_tx_data_bus_reg[36] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_91), .Q (can_tx_data_bus[36]));
  DFFQSRX1 \can_tx_data_bus_reg[37] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_117), .Q (can_tx_data_bus[37]));
  DFFQSRX1 \can_tx_data_bus_reg[38] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_64), .Q (can_tx_data_bus[38]));
  DFFQSRX1 \can_tx_data_bus_reg[39] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_62), .Q (can_tx_data_bus[39]));
  DFFQSRX1 \can_tx_data_bus_reg[40] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_61), .Q (can_tx_data_bus[40]));
  DFFQSRX1 \can_tx_data_bus_reg[41] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_73), .Q (can_tx_data_bus[41]));
  DFFQSRX1 \can_tx_data_bus_reg[42] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_96), .Q (can_tx_data_bus[42]));
  DFFQSRX1 \can_tx_data_bus_reg[43] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_124), .Q (can_tx_data_bus[43]));
  DFFQSRX1 \can_tx_data_bus_reg[44] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_113), .Q (can_tx_data_bus[44]));
  DFFQSRX1 \can_tx_data_bus_reg[45] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_69), .Q (can_tx_data_bus[45]));
  DFFQSRX1 \can_tx_data_bus_reg[46] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_77), .Q (can_tx_data_bus[46]));
  DFFQSRX1 \can_tx_data_bus_reg[47] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_119), .Q (can_tx_data_bus[47]));
  DFFQSRX1 \can_tx_data_bus_reg[48] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_121), .Q (can_tx_data_bus[48]));
  DFFQSRX1 \can_tx_data_bus_reg[49] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_65), .Q (can_tx_data_bus[49]));
  DFFQSRX1 \can_tx_data_bus_reg[50] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_116), .Q (can_tx_data_bus[50]));
  DFFQSRX1 \can_tx_data_bus_reg[51] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_72), .Q (can_tx_data_bus[51]));
  DFFQSRX1 \can_tx_data_bus_reg[52] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_111), .Q (can_tx_data_bus[52]));
  DFFQSRX1 \can_tx_data_bus_reg[53] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_108), .Q (can_tx_data_bus[53]));
  DFFQSRX1 \can_tx_data_bus_reg[54] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_88), .Q (can_tx_data_bus[54]));
  DFFQSRX1 \can_tx_data_bus_reg[55] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_106), .Q (can_tx_data_bus[55]));
  DFFQSRX1 \can_tx_data_bus_reg[56] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_103), .Q (can_tx_data_bus[56]));
  DFFQSRX1 \can_tx_data_bus_reg[57] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_101), .Q (can_tx_data_bus[57]));
  DFFQSRX1 \can_tx_data_bus_reg[58] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_99), .Q (can_tx_data_bus[58]));
  DFFQSRX1 \can_tx_data_bus_reg[59] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_97), .Q (can_tx_data_bus[59]));
  DFFQSRX1 \can_tx_data_bus_reg[60] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_95), .Q (can_tx_data_bus[60]));
  DFFQSRX1 \can_tx_data_bus_reg[61] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_92), .Q (can_tx_data_bus[61]));
  DFFQSRX1 \can_tx_data_bus_reg[62] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_89), .Q (can_tx_data_bus[62]));
  DFFQSRX1 \can_tx_data_bus_reg[63] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clock), .D (n_87), .Q (can_tx_data_bus[63]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[0] (.SETB (1'b1), .RESETB (n_13),
       .CLK (clock), .D (n_472), .Q (can_tx_inst_shift_reg[0]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[1] (.SETB (1'b1), .RESETB (n_13),
       .CLK (clock), .D (n_508), .Q (can_tx_inst_shift_reg[1]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[2] (.SETB (1'b1), .RESETB (n_13),
       .CLK (clock), .D (n_471), .Q (can_tx_inst_shift_reg[2]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[3] (.SETB (1'b1), .RESETB (n_13),
       .CLK (clock), .D (n_473), .Q (can_tx_inst_shift_reg[3]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[4] (.SETB (1'b1), .RESETB (n_13),
       .CLK (clock), .D (n_500), .Q (can_tx_inst_shift_reg[4]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[5] (.SETB (1'b1), .RESETB (n_13),
       .CLK (clock), .D (n_470), .Q (can_tx_inst_shift_reg[5]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[6] (.SETB (1'b1), .RESETB (n_13),
       .CLK (clock), .D (n_469), .Q (can_tx_inst_shift_reg[6]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[7] (.SETB (1'b1), .RESETB (n_13),
       .CLK (clock), .D (n_468), .Q (can_tx_inst_shift_reg[7]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[8] (.SETB (1'b1), .RESETB (n_13),
       .CLK (clock), .D (n_466), .Q (can_tx_inst_shift_reg[8]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[9] (.SETB (1'b1), .RESETB (n_13),
       .CLK (clock), .D (n_467), .Q (can_tx_inst_shift_reg[9]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[10] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_285), .Q
       (can_tx_inst_shift_reg[10]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[11] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_499), .Q
       (can_tx_inst_shift_reg[11]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[12] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_498), .Q
       (can_tx_inst_shift_reg[12]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[13] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_497), .Q
       (can_tx_inst_shift_reg[13]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[14] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_496), .Q
       (can_tx_inst_shift_reg[14]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[15] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_494), .Q
       (can_tx_inst_shift_reg[15]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[16] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_495), .Q
       (can_tx_inst_shift_reg[16]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[17] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_491), .Q
       (can_tx_inst_shift_reg[17]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[18] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_489), .Q
       (can_tx_inst_shift_reg[18]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[19] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_486), .Q
       (can_tx_inst_shift_reg[19]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[20] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_513), .Q
       (can_tx_inst_shift_reg[20]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[21] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_512), .Q
       (can_tx_inst_shift_reg[21]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[22] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_511), .Q
       (can_tx_inst_shift_reg[22]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[23] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_510), .Q
       (can_tx_inst_shift_reg[23]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[24] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_509), .Q
       (can_tx_inst_shift_reg[24]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[25] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_567), .Q
       (can_tx_inst_shift_reg[25]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[26] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_570), .Q
       (can_tx_inst_shift_reg[26]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[27] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_569), .Q
       (can_tx_inst_shift_reg[27]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[28] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_568), .Q
       (can_tx_inst_shift_reg[28]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[29] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_565), .Q
       (can_tx_inst_shift_reg[29]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[30] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_566), .Q
       (can_tx_inst_shift_reg[30]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[31] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_564), .Q
       (can_tx_inst_shift_reg[31]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[32] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_576), .Q
       (can_tx_inst_shift_reg[32]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[33] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_575), .Q
       (can_tx_inst_shift_reg[33]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[34] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_563), .Q
       (can_tx_inst_shift_reg[34]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[35] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_535), .Q
       (can_tx_inst_shift_reg[35]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[36] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_561), .Q
       (can_tx_inst_shift_reg[36]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[37] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_560), .Q
       (can_tx_inst_shift_reg[37]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[38] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_559), .Q
       (can_tx_inst_shift_reg[38]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[39] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_558), .Q
       (can_tx_inst_shift_reg[39]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[40] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_557), .Q
       (can_tx_inst_shift_reg[40]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[41] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_556), .Q
       (can_tx_inst_shift_reg[41]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[42] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_555), .Q
       (can_tx_inst_shift_reg[42]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[43] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_554), .Q
       (can_tx_inst_shift_reg[43]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[44] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_553), .Q
       (can_tx_inst_shift_reg[44]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[45] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_552), .Q
       (can_tx_inst_shift_reg[45]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[46] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_551), .Q
       (can_tx_inst_shift_reg[46]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[47] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_550), .Q
       (can_tx_inst_shift_reg[47]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[48] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_549), .Q
       (can_tx_inst_shift_reg[48]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[49] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_548), .Q
       (can_tx_inst_shift_reg[49]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[50] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_547), .Q
       (can_tx_inst_shift_reg[50]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[51] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_546), .Q
       (can_tx_inst_shift_reg[51]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[52] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_545), .Q
       (can_tx_inst_shift_reg[52]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[53] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_544), .Q
       (can_tx_inst_shift_reg[53]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[54] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_543), .Q
       (can_tx_inst_shift_reg[54]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[55] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_542), .Q
       (can_tx_inst_shift_reg[55]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[56] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_541), .Q
       (can_tx_inst_shift_reg[56]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[57] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_540), .Q
       (can_tx_inst_shift_reg[57]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[58] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_539), .Q
       (can_tx_inst_shift_reg[58]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[59] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_538), .Q
       (can_tx_inst_shift_reg[59]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[60] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_537), .Q
       (can_tx_inst_shift_reg[60]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[61] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_562), .Q
       (can_tx_inst_shift_reg[61]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[62] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_536), .Q
       (can_tx_inst_shift_reg[62]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[63] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_534), .Q
       (can_tx_inst_shift_reg[63]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[64] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_533), .Q
       (can_tx_inst_shift_reg[64]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[65] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_532), .Q
       (can_tx_inst_shift_reg[65]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[66] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_531), .Q
       (can_tx_inst_shift_reg[66]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[67] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_530), .Q
       (can_tx_inst_shift_reg[67]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[68] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_529), .Q
       (can_tx_inst_shift_reg[68]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[69] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_528), .Q
       (can_tx_inst_shift_reg[69]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[70] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_527), .Q
       (can_tx_inst_shift_reg[70]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[71] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_526), .Q
       (can_tx_inst_shift_reg[71]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[72] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_525), .Q
       (can_tx_inst_shift_reg[72]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[73] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_524), .Q
       (can_tx_inst_shift_reg[73]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[74] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_523), .Q
       (can_tx_inst_shift_reg[74]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[75] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_522), .Q
       (can_tx_inst_shift_reg[75]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[76] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_521), .Q
       (can_tx_inst_shift_reg[76]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[77] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_520), .Q
       (can_tx_inst_shift_reg[77]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[78] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_519), .Q
       (can_tx_inst_shift_reg[78]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[79] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_518), .Q
       (can_tx_inst_shift_reg[79]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[80] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_517), .Q
       (can_tx_inst_shift_reg[80]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[81] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_516), .Q
       (can_tx_inst_shift_reg[81]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[82] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_515), .Q
       (can_tx_inst_shift_reg[82]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[83] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_514), .Q
       (can_tx_inst_shift_reg[83]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[84] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_493), .Q
       (can_tx_inst_shift_reg[84]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[85] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_492), .Q
       (can_tx_inst_shift_reg[85]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[86] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_490), .Q
       (can_tx_inst_shift_reg[86]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[87] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_488), .Q
       (can_tx_inst_shift_reg[87]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[88] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_487), .Q
       (can_tx_inst_shift_reg[88]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[89] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_485), .Q
       (can_tx_inst_shift_reg[89]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[90] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_484), .Q
       (can_tx_inst_shift_reg[90]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[91] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_483), .Q
       (can_tx_inst_shift_reg[91]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[92] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_482), .Q
       (can_tx_inst_shift_reg[92]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[93] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_481), .Q
       (can_tx_inst_shift_reg[93]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[94] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_480), .Q
       (can_tx_inst_shift_reg[94]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[95] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_479), .Q
       (can_tx_inst_shift_reg[95]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[96] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_478), .Q
       (can_tx_inst_shift_reg[96]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[97] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_477), .Q
       (can_tx_inst_shift_reg[97]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[98] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_476), .Q
       (can_tx_inst_shift_reg[98]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[99] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_284), .Q
       (can_tx_inst_shift_reg[99]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[100] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_475), .Q
       (can_tx_inst_shift_reg[100]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[101] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_474), .Q
       (can_tx_inst_shift_reg[101]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[102] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_283), .Q
       (can_tx_inst_shift_reg[102]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[103] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_288), .Q
       (can_tx_inst_shift_reg[103]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[104] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_287), .Q
       (can_tx_inst_shift_reg[104]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[105] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_286), .Q
       (can_tx_inst_shift_reg[105]));
  DFFQSRX1 \can_tx_inst_shift_reg_reg[106] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_383), .Q
       (can_tx_inst_shift_reg[106]));
  DFFQSRX1 \can_tx_inst_state_reg[0] (.SETB (n_13), .RESETB (1'b1),
       .CLK (clock), .D (n_571), .Q (can_tx_inst_state[0]));
  DFFQSRX1 \can_tx_inst_state_reg[1] (.SETB (n_13), .RESETB (1'b1),
       .CLK (clock), .D (n_249), .Q (can_tx_inst_state[1]));
  DFFQSRX1 \can_tx_inst_status_reg_reg[0] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_246), .Q
       (can_tx_inst_status_reg[0]));
  DFFQSRX1 \can_tx_inst_status_reg_reg[1] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_602), .Q
       (can_tx_inst_status_reg[1]));
  DFFQSRX1 \can_tx_inst_status_reg_reg[2] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_506), .Q
       (can_tx_inst_status_reg[2]));
  DFFQSRX1 \can_tx_inst_status_reg_reg[3] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_574), .Q
       (can_tx_inst_status_reg[3]));
  DFFQSRX1 \can_tx_inst_status_reg_reg[4] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_579), .Q
       (can_tx_inst_status_reg[4]));
  DFFQSRX1 \can_tx_inst_status_reg_reg[5] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_583), .Q
       (can_tx_inst_status_reg[5]));
  DFFQSRX1 \can_tx_inst_status_reg_reg[6] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_585), .Q
       (can_tx_inst_status_reg[6]));
  DFFQSRX1 \uart_rx_inst_bit_count_reg[0] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_347), .Q
       (uart_rx_inst_bit_count[0]));
  DFFQSRX1 \uart_rx_inst_bit_count_reg[1] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_501), .Q
       (uart_rx_inst_bit_count[1]));
  DFFQSRX1 \uart_rx_inst_bit_count_reg[2] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_573), .Q
       (uart_rx_inst_bit_count[2]));
  DFFQSRX1 \uart_rx_inst_bit_count_reg[3] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_582), .Q
       (uart_rx_inst_bit_count[3]));
  DFFQSRX1 \uart_rx_inst_shift_reg_reg[1] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_281), .Q
       (uart_rx_inst_shift_reg[1]));
  DFFQSRX1 \uart_rx_inst_shift_reg_reg[2] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_280), .Q
       (uart_rx_inst_shift_reg[2]));
  DFFQSRX1 \uart_rx_inst_shift_reg_reg[3] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_279), .Q
       (uart_rx_inst_shift_reg[3]));
  DFFQSRX1 \uart_rx_inst_shift_reg_reg[4] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_278), .Q
       (uart_rx_inst_shift_reg[4]));
  DFFQSRX1 \uart_rx_inst_shift_reg_reg[5] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_277), .Q
       (uart_rx_inst_shift_reg[5]));
  DFFQSRX1 \uart_rx_inst_shift_reg_reg[6] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_273), .Q
       (uart_rx_inst_shift_reg[6]));
  DFFQSRX1 \uart_rx_inst_shift_reg_reg[7] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_276), .Q
       (uart_rx_inst_shift_reg[7]));
  DFFQSRX1 \uart_rx_inst_shift_reg_reg[8] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_275), .Q
       (uart_rx_inst_shift_reg[8]));
  DFFQSRX1 \uart_rx_inst_shift_reg_reg[9] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_274), .Q
       (uart_rx_inst_shift_reg[9]));
  DFFQSRX1 \uart_rx_inst_state_reg[0] (.SETB (n_13), .RESETB (1'b1),
       .CLK (clock), .D (n_412), .Q (uart_rx_inst_state[0]));
  DFFQSRX1 \uart_rx_inst_state_reg[1] (.SETB (n_13), .RESETB (1'b1),
       .CLK (clock), .D (n_252), .Q (uart_rx_inst_state[1]));
  DFFQSRX1 uart_rx_inst_uart_data_ready_reg(.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_257), .Q (uart_data_ready));
  DFFQSRX1 \uart_rx_inst_uart_rx_data_bus_reg[0] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_271), .Q (uart_rx_data_bus[0]));
  DFFQSRX1 \uart_rx_inst_uart_rx_data_bus_reg[1] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_270), .Q (uart_rx_data_bus[1]));
  DFFQSRX1 \uart_rx_inst_uart_rx_data_bus_reg[2] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_269), .Q (uart_rx_data_bus[2]));
  DFFQSRX1 \uart_rx_inst_uart_rx_data_bus_reg[3] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_265), .Q (uart_rx_data_bus[3]));
  DFFQSRX1 \uart_rx_inst_uart_rx_data_bus_reg[4] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_268), .Q (uart_rx_data_bus[4]));
  DFFQSRX1 \uart_rx_inst_uart_rx_data_bus_reg[5] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_267), .Q (uart_rx_data_bus[5]));
  DFFQSRX1 \uart_rx_inst_uart_rx_data_bus_reg[6] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_266), .Q (uart_rx_data_bus[6]));
  DFFQSRX1 \uart_rx_inst_uart_rx_data_bus_reg[7] (.SETB (n_13), .RESETB
       (1'b1), .CLK (clock), .D (n_272), .Q (uart_rx_data_bus[7]));
  NAND2X1 g8430__5526(.A (n_584), .B (n_376), .Z (n_585));
  NAND2X1 g8433__6783(.A (n_581), .B (can_tx_inst_status_reg[6]), .Z
       (n_584));
  NAND2X1 g8434__3680(.A (n_580), .B (n_289), .Z (n_583));
  NAND2X1 g8470__1617(.A (n_572), .B (n_370), .Z (n_582));
  NAND2X1 g8471__2802(.A (n_577), .B (n_28), .Z (n_581));
  NAND2X1 g8472__1705(.A (n_578), .B (can_tx_inst_status_reg[5]), .Z
       (n_580));
  MUX2X1 g8473__5122(.A (n_261), .B (n_502), .S
       (can_tx_inst_status_reg[4]), .Z (n_579));
  INVX2 g8506(.A (n_577), .Z (n_578));
  NAND3X1 g8507__8246(.A (n_374), .B (n_440), .C (n_191), .Z (n_576));
  NAND3X1 g8508__7098(.A (n_371), .B (n_439), .C (n_217), .Z (n_575));
  NAND2X1 g8509__6131(.A (n_247), .B (n_504), .Z (n_574));
  NAND2X1 g8510__1881(.A (n_373), .B (n_503), .Z (n_573));
  NAND2X1 g8511__5115(.A (n_507), .B (uart_rx_inst_bit_count[3]), .Z
       (n_572));
  NAND3X1 g8512__7482(.A (n_11), .B (n_505), .C (n_44), .Z (n_571));
  NAND3X1 g8513__4733(.A (n_382), .B (n_446), .C (n_225), .Z (n_570));
  NAND3X1 g8514__6161(.A (n_381), .B (n_445), .C (n_222), .Z (n_569));
  NAND3X1 g8515__9315(.A (n_379), .B (n_444), .C (n_172), .Z (n_568));
  NAND3X1 g8516__9945(.A (n_384), .B (n_447), .C (n_227), .Z (n_567));
  NAND3X1 g8517__2883(.A (n_377), .B (n_442), .C (n_220), .Z (n_566));
  NAND3X1 g8518__2346(.A (n_378), .B (n_443), .C (n_209), .Z (n_565));
  NAND3X1 g8519__1666(.A (n_375), .B (n_441), .C (n_219), .Z (n_564));
  NAND3X1 g8520__7410(.A (n_369), .B (n_438), .C (n_215), .Z (n_563));
  NOR2X1 g8546__6417(.A (n_36), .B (n_502), .Z (n_577));
  NAND3X1 g8560__5477(.A (n_344), .B (n_411), .C (n_180), .Z (n_562));
  NAND3X1 g8561__2398(.A (n_372), .B (n_436), .C (n_167), .Z (n_561));
  NAND3X1 g8562__5107(.A (n_459), .B (n_435), .C (n_185), .Z (n_560));
  NAND3X1 g8563__6260(.A (n_460), .B (n_434), .C (n_205), .Z (n_559));
  NAND3X1 g8564__4319(.A (n_461), .B (n_433), .C (n_221), .Z (n_558));
  NAND3X1 g8565__8428(.A (n_462), .B (n_432), .C (n_214), .Z (n_557));
  NAND3X1 g8566__5526(.A (n_315), .B (n_431), .C (n_213), .Z (n_556));
  NAND3X1 g8567__6783(.A (n_365), .B (n_430), .C (n_212), .Z (n_555));
  NAND3X1 g8568__3680(.A (n_364), .B (n_429), .C (n_210), .Z (n_554));
  NAND3X1 g8569__1617(.A (n_363), .B (n_428), .C (n_208), .Z (n_553));
  NAND3X1 g8570__2802(.A (n_362), .B (n_427), .C (n_206), .Z (n_552));
  NAND3X1 g8571__1705(.A (n_361), .B (n_426), .C (n_204), .Z (n_551));
  NAND3X1 g8572__5122(.A (n_360), .B (n_425), .C (n_203), .Z (n_550));
  NAND3X1 g8573__8246(.A (n_359), .B (n_424), .C (n_202), .Z (n_549));
  NAND3X1 g8574__7098(.A (n_358), .B (n_423), .C (n_201), .Z (n_548));
  NAND3X1 g8575__6131(.A (n_357), .B (n_422), .C (n_199), .Z (n_547));
  NAND3X1 g8576__1881(.A (n_356), .B (n_421), .C (n_198), .Z (n_546));
  NAND3X1 g8577__5115(.A (n_354), .B (n_420), .C (n_196), .Z (n_545));
  NAND3X1 g8578__7482(.A (n_353), .B (n_419), .C (n_194), .Z (n_544));
  NAND3X1 g8579__4733(.A (n_352), .B (n_418), .C (n_193), .Z (n_543));
  NAND3X1 g8580__6161(.A (n_351), .B (n_417), .C (n_192), .Z (n_542));
  NAND3X1 g8581__9315(.A (n_350), .B (n_416), .C (n_188), .Z (n_541));
  NAND3X1 g8582__9945(.A (n_349), .B (n_415), .C (n_186), .Z (n_540));
  NAND3X1 g8583__2883(.A (n_348), .B (n_414), .C (n_184), .Z (n_539));
  NAND3X1 g8584__2346(.A (n_346), .B (n_413), .C (n_183), .Z (n_538));
  NAND3X1 g8585__1666(.A (n_345), .B (n_463), .C (n_181), .Z (n_537));
  NAND3X1 g8586__7410(.A (n_343), .B (n_410), .C (n_179), .Z (n_536));
  NAND3X1 g8587__6417(.A (n_368), .B (n_437), .C (n_169), .Z (n_535));
  NAND3X1 g8588__5477(.A (n_342), .B (n_409), .C (n_177), .Z (n_534));
  NAND3X1 g8589__2398(.A (n_341), .B (n_408), .C (n_175), .Z (n_533));
  NAND3X1 g8590__5107(.A (n_340), .B (n_407), .C (n_174), .Z (n_532));
  NAND3X1 g8591__6260(.A (n_339), .B (n_406), .C (n_173), .Z (n_531));
  NAND3X1 g8592__4319(.A (n_338), .B (n_405), .C (n_171), .Z (n_530));
  NAND3X1 g8593__8428(.A (n_337), .B (n_404), .C (n_170), .Z (n_529));
  NAND3X1 g8594__5526(.A (n_336), .B (n_403), .C (n_168), .Z (n_528));
  NAND3X1 g8595__6783(.A (n_335), .B (n_402), .C (n_166), .Z (n_527));
  NAND3X1 g8596__3680(.A (n_334), .B (n_401), .C (n_165), .Z (n_526));
  NAND3X1 g8597__1617(.A (n_333), .B (n_400), .C (n_164), .Z (n_525));
  NAND3X1 g8598__2802(.A (n_332), .B (n_399), .C (n_163), .Z (n_524));
  NAND3X1 g8599__1705(.A (n_331), .B (n_398), .C (n_160), .Z (n_523));
  NAND3X1 g8600__5122(.A (n_330), .B (n_397), .C (n_159), .Z (n_522));
  NAND3X1 g8601__8246(.A (n_328), .B (n_396), .C (n_158), .Z (n_521));
  NAND3X1 g8602__7098(.A (n_327), .B (n_395), .C (n_156), .Z (n_520));
  NAND3X1 g8603__6131(.A (n_325), .B (n_394), .C (n_154), .Z (n_519));
  NAND3X1 g8604__1881(.A (n_324), .B (n_393), .C (n_152), .Z (n_518));
  NAND3X1 g8605__5115(.A (n_323), .B (n_392), .C (n_218), .Z (n_517));
  NAND3X1 g8606__7482(.A (n_320), .B (n_391), .C (n_226), .Z (n_516));
  NAND3X1 g8607__4733(.A (n_318), .B (n_390), .C (n_127), .Z (n_515));
  NAND3X1 g8608__6161(.A (n_317), .B (n_389), .C (n_146), .Z (n_514));
  NAND3X1 g8609__9315(.A (n_306), .B (n_388), .C (n_157), .Z (n_513));
  NAND3X1 g8610__9945(.A (n_301), .B (n_387), .C (n_162), .Z (n_512));
  NAND3X1 g8611__2883(.A (n_296), .B (n_386), .C (n_132), .Z (n_511));
  NAND3X1 g8612__2346(.A (n_294), .B (n_385), .C (n_130), .Z (n_510));
  NAND3X1 g8613__1666(.A (n_291), .B (n_448), .C (n_230), .Z (n_509));
  OR2X1 g8614__7410(.A (n_60), .B (n_367), .Z (n_508));
  NAND2X1 g8615__6417(.A (n_464), .B (n_50), .Z (n_507));
  NAND2X1 g8616__5477(.A (n_248), .B (n_449), .Z (n_506));
  NAND3X1 g8617__2398(.A (n_7), .B (n_30), .C (n_256), .Z (n_505));
  NAND2X1 g8618__5107(.A (n_290), .B (can_tx_inst_status_reg[3]), .Z
       (n_504));
  NAND2X1 g8619__6260(.A (n_465), .B (uart_rx_inst_bit_count[2]), .Z
       (n_503));
  MUX2X1 g8650__4319(.A (n_263), .B (n_264), .S
       (uart_rx_inst_bit_count[1]), .Z (n_501));
  OR2X1 g8651__8428(.A (n_148), .B (n_367), .Z (n_500));
  NAND2X1 g8652__5526(.A (n_329), .B (n_195), .Z (n_499));
  NAND2X1 g8653__6783(.A (n_326), .B (n_155), .Z (n_498));
  NAND2X1 g8654__3680(.A (n_322), .B (n_207), .Z (n_497));
  NAND2X1 g8655__1617(.A (n_321), .B (n_234), .Z (n_496));
  NAND2X1 g8656__2802(.A (n_316), .B (n_147), .Z (n_495));
  NAND2X1 g8657__1705(.A (n_319), .B (n_236), .Z (n_494));
  NAND2X1 g8658__5122(.A (n_366), .B (n_145), .Z (n_493));
  NAND2X1 g8659__8246(.A (n_314), .B (n_197), .Z (n_492));
  NAND2X1 g8660__7098(.A (n_312), .B (n_144), .Z (n_491));
  NAND2X1 g8661__6131(.A (n_313), .B (n_143), .Z (n_490));
  NAND2X1 g8662__1881(.A (n_311), .B (n_141), .Z (n_489));
  NAND2X1 g8663__5115(.A (n_310), .B (n_142), .Z (n_488));
  NAND2X1 g8664__7482(.A (n_309), .B (n_134), .Z (n_487));
  NAND2X1 g8665__4733(.A (n_307), .B (n_140), .Z (n_486));
  NAND2X1 g8666__6161(.A (n_308), .B (n_139), .Z (n_485));
  NAND2X1 g8667__9315(.A (n_305), .B (n_138), .Z (n_484));
  NAND2X1 g8668__9945(.A (n_304), .B (n_182), .Z (n_483));
  NAND2X1 g8669__2883(.A (n_303), .B (n_137), .Z (n_482));
  NAND2X1 g8670__2346(.A (n_302), .B (n_153), .Z (n_481));
  NAND2X1 g8671__1666(.A (n_300), .B (n_136), .Z (n_480));
  NAND2X1 g8672__7410(.A (n_299), .B (n_135), .Z (n_479));
  NAND2X1 g8673__6417(.A (n_298), .B (n_176), .Z (n_478));
  NAND2X1 g8674__5477(.A (n_297), .B (n_133), .Z (n_477));
  NAND2X1 g8675__2398(.A (n_295), .B (n_131), .Z (n_476));
  NAND2X1 g8676__5107(.A (n_293), .B (n_211), .Z (n_475));
  NAND2X1 g8677__6260(.A (n_292), .B (n_129), .Z (n_474));
  OR2X1 g8678__4319(.A (n_126), .B (n_367), .Z (n_473));
  NAND3X1 g8679__8428(.A (n_456), .B (n_593), .C (n_32), .Z (n_472));
  NAND3X1 g8680__5526(.A (n_455), .B (n_593), .C (n_24), .Z (n_471));
  NAND3X1 g8681__6783(.A (n_454), .B (n_593), .C (n_21), .Z (n_470));
  NAND3X1 g8682__3680(.A (n_453), .B (n_593), .C (n_25), .Z (n_469));
  NAND3X1 g8683__1617(.A (n_452), .B (n_593), .C (n_27), .Z (n_468));
  NAND3X1 g8684__2802(.A (n_450), .B (n_593), .C (n_33), .Z (n_467));
  NAND3X1 g8685__1705(.A (n_451), .B (n_593), .C (n_34), .Z (n_466));
  NAND2X1 g8686__5122(.A (n_457), .B (n_3), .Z (n_502));
  INVX2 g8687(.A (n_464), .Z (n_465));
  NAND2X1 g8688__8246(.A (n_259), .B (can_tx_data_bus[40]), .Z (n_463));
  NAND2X1 g8689__7098(.A (n_0), .B (can_tx_inst_shift_reg[40]), .Z
       (n_462));
  NAND2X1 g8690__6131(.A (n_258), .B (can_tx_inst_shift_reg[39]), .Z
       (n_461));
  NAND2X1 g8691__1881(.A (n_0), .B (can_tx_inst_shift_reg[38]), .Z
       (n_460));
  NAND2X1 g8692__5115(.A (n_258), .B (can_tx_inst_shift_reg[37]), .Z
       (n_459));
  OR2X1 g8693__7482(.A (Can_ID_Bus[0]), .B (n_262), .Z (n_458));
  NAND2X1 g8694__4733(.A (n_255), .B (n_5), .Z (n_457));
  NAND2X1 g8695__6161(.A (n_260), .B (can_tx_inst_shift_reg[0]), .Z
       (n_456));
  NAND2X1 g8696__9315(.A (n_260), .B (can_tx_inst_shift_reg[2]), .Z
       (n_455));
  NAND2X1 g8697__9945(.A (n_260), .B (can_tx_inst_shift_reg[5]), .Z
       (n_454));
  NAND2X1 g8698__2883(.A (n_260), .B (can_tx_inst_shift_reg[6]), .Z
       (n_453));
  NAND2X1 g8699__2346(.A (n_260), .B (can_tx_inst_shift_reg[7]), .Z
       (n_452));
  NAND2X1 g8700__1666(.A (n_260), .B (can_tx_inst_shift_reg[8]), .Z
       (n_451));
  NAND2X1 g8701__7410(.A (n_260), .B (can_tx_inst_shift_reg[9]), .Z
       (n_450));
  NAND2X1 g8702__6417(.A (n_245), .B (can_tx_inst_status_reg[2]), .Z
       (n_449));
  NAND2X1 g8703__5477(.A (n_259), .B (can_tx_data_bus[4]), .Z (n_448));
  NAND2X1 g8704__2398(.A (n_259), .B (can_tx_data_bus[5]), .Z (n_447));
  NAND2X1 g8705__5107(.A (n_259), .B (can_tx_data_bus[6]), .Z (n_446));
  NAND2X1 g8706__6260(.A (n_259), .B (can_tx_data_bus[7]), .Z (n_445));
  NAND2X1 g8707__4319(.A (n_259), .B (can_tx_data_bus[8]), .Z (n_444));
  NAND2X1 g8708__8428(.A (n_259), .B (can_tx_data_bus[9]), .Z (n_443));
  NAND2X1 g8709__5526(.A (n_259), .B (can_tx_data_bus[10]), .Z (n_442));
  NAND2X1 g8710__6783(.A (n_259), .B (can_tx_data_bus[11]), .Z (n_441));
  NAND2X1 g8711__3680(.A (n_259), .B (can_tx_data_bus[12]), .Z (n_440));
  NAND2X1 g8712__1617(.A (n_259), .B (can_tx_data_bus[13]), .Z (n_439));
  NAND2X1 g8713__2802(.A (n_259), .B (can_tx_data_bus[14]), .Z (n_438));
  NAND2X1 g8714__1705(.A (n_259), .B (can_tx_data_bus[15]), .Z (n_437));
  NAND2X1 g8715__5122(.A (n_259), .B (can_tx_data_bus[16]), .Z (n_436));
  NAND2X1 g8716__8246(.A (n_259), .B (can_tx_data_bus[17]), .Z (n_435));
  NAND2X1 g8717__7098(.A (n_259), .B (can_tx_data_bus[18]), .Z (n_434));
  NAND2X1 g8718__6131(.A (n_259), .B (can_tx_data_bus[19]), .Z (n_433));
  NAND2X1 g8719__1881(.A (n_259), .B (can_tx_data_bus[20]), .Z (n_432));
  NAND2X1 g8720__5115(.A (n_259), .B (can_tx_data_bus[21]), .Z (n_431));
  NAND2X1 g8721__7482(.A (n_259), .B (can_tx_data_bus[22]), .Z (n_430));
  NAND2X1 g8722__4733(.A (n_259), .B (can_tx_data_bus[23]), .Z (n_429));
  NAND2X1 g8723__6161(.A (n_259), .B (can_tx_data_bus[24]), .Z (n_428));
  NAND2X1 g8724__9315(.A (n_259), .B (can_tx_data_bus[25]), .Z (n_427));
  NAND2X1 g8725__9945(.A (n_259), .B (can_tx_data_bus[26]), .Z (n_426));
  NAND2X1 g8726__2883(.A (n_259), .B (can_tx_data_bus[27]), .Z (n_425));
  NAND2X1 g8727__2346(.A (n_259), .B (can_tx_data_bus[28]), .Z (n_424));
  NAND2X1 g8728__1666(.A (n_259), .B (can_tx_data_bus[29]), .Z (n_423));
  NAND2X1 g8729__7410(.A (n_259), .B (can_tx_data_bus[30]), .Z (n_422));
  NAND2X1 g8730__6417(.A (n_259), .B (can_tx_data_bus[31]), .Z (n_421));
  NAND2X1 g8731__5477(.A (n_259), .B (can_tx_data_bus[32]), .Z (n_420));
  NAND2X1 g8732__2398(.A (n_259), .B (can_tx_data_bus[33]), .Z (n_419));
  NAND2X1 g8733__5107(.A (n_259), .B (can_tx_data_bus[34]), .Z (n_418));
  NAND2X1 g8734__6260(.A (n_259), .B (can_tx_data_bus[35]), .Z (n_417));
  NAND2X1 g8735__4319(.A (n_259), .B (can_tx_data_bus[36]), .Z (n_416));
  NAND2X1 g8736__8428(.A (n_259), .B (can_tx_data_bus[37]), .Z (n_415));
  NAND2X1 g8737__5526(.A (n_259), .B (can_tx_data_bus[38]), .Z (n_414));
  NAND2X1 g8738__6783(.A (n_259), .B (can_tx_data_bus[39]), .Z (n_413));
  NAND3X1 g8739__3680(.A (n_250), .B (n_235), .C (n_54), .Z (n_412));
  NAND2X1 g8740__1617(.A (n_259), .B (can_tx_data_bus[41]), .Z (n_411));
  NAND2X1 g8741__2802(.A (n_259), .B (can_tx_data_bus[42]), .Z (n_410));
  NAND2X1 g8742__1705(.A (n_259), .B (can_tx_data_bus[43]), .Z (n_409));
  NAND2X1 g8743__5122(.A (n_259), .B (can_tx_data_bus[44]), .Z (n_408));
  NAND2X1 g8744__8246(.A (n_259), .B (can_tx_data_bus[45]), .Z (n_407));
  NAND2X1 g8745__7098(.A (n_259), .B (can_tx_data_bus[46]), .Z (n_406));
  NAND2X1 g8746__6131(.A (n_259), .B (can_tx_data_bus[47]), .Z (n_405));
  NAND2X1 g8747__1881(.A (n_259), .B (can_tx_data_bus[48]), .Z (n_404));
  NAND2X1 g8748__5115(.A (n_259), .B (can_tx_data_bus[49]), .Z (n_403));
  NAND2X1 g8749__7482(.A (n_259), .B (can_tx_data_bus[50]), .Z (n_402));
  NAND2X1 g8750__4733(.A (n_259), .B (can_tx_data_bus[51]), .Z (n_401));
  NAND2X1 g8751__6161(.A (n_259), .B (can_tx_data_bus[52]), .Z (n_400));
  NAND2X1 g8752__9315(.A (n_259), .B (can_tx_data_bus[53]), .Z (n_399));
  NAND2X1 g8753__9945(.A (n_259), .B (can_tx_data_bus[54]), .Z (n_398));
  NAND2X1 g8754__2883(.A (n_259), .B (can_tx_data_bus[55]), .Z (n_397));
  NAND2X1 g8755__2346(.A (n_10), .B (can_tx_data_bus[56]), .Z (n_396));
  NAND2X1 g8756__1666(.A (n_10), .B (can_tx_data_bus[57]), .Z (n_395));
  NAND2X1 g8757__7410(.A (n_10), .B (can_tx_data_bus[58]), .Z (n_394));
  NAND2X1 g8758__6417(.A (n_10), .B (can_tx_data_bus[59]), .Z (n_393));
  NAND2X1 g8759__5477(.A (n_10), .B (can_tx_data_bus[60]), .Z (n_392));
  NAND2X1 g8760__2398(.A (n_10), .B (can_tx_data_bus[61]), .Z (n_391));
  NAND2X1 g8761__5107(.A (n_10), .B (can_tx_data_bus[62]), .Z (n_390));
  NAND2X1 g8762__6260(.A (n_10), .B (can_tx_data_bus[63]), .Z (n_389));
  NAND2X1 g8763__4319(.A (n_259), .B (can_tx_data_bus[0]), .Z (n_388));
  NAND2X1 g8764__8428(.A (n_259), .B (can_tx_data_bus[1]), .Z (n_387));
  NAND2X1 g8765__5526(.A (n_259), .B (can_tx_data_bus[2]), .Z (n_386));
  NAND2X1 g8766__6783(.A (n_259), .B (can_tx_data_bus[3]), .Z (n_385));
  NAND2X1 g8767__3680(.A (n_0), .B (can_tx_inst_shift_reg[25]), .Z
       (n_384));
  NAND2X1 g8768__1617(.A (n_11), .B (n_46), .Z (n_383));
  NAND2X1 g8769__2802(.A (n_0), .B (can_tx_inst_shift_reg[26]), .Z
       (n_382));
  NAND2X1 g8770__1705(.A (n_0), .B (can_tx_inst_shift_reg[27]), .Z
       (n_381));
  NAND2X1 g8772__8246(.A (n_258), .B (can_tx_inst_shift_reg[28]), .Z
       (n_379));
  NAND2X1 g8773__7098(.A (n_0), .B (can_tx_inst_shift_reg[29]), .Z
       (n_378));
  NAND2X1 g8774__6131(.A (n_0), .B (can_tx_inst_shift_reg[30]), .Z
       (n_377));
  NAND3X1 g8775__1881(.A (n_261), .B (n_56), .C
       (can_tx_inst_status_reg[4]), .Z (n_376));
  NAND2X1 g8776__5115(.A (n_258), .B (can_tx_inst_shift_reg[31]), .Z
       (n_375));
  NAND2X1 g8777__7482(.A (n_258), .B (can_tx_inst_shift_reg[32]), .Z
       (n_374));
  NAND3X1 g8778__4733(.A (n_263), .B (n_16), .C
       (uart_rx_inst_bit_count[1]), .Z (n_373));
  NAND2X1 g8779__6161(.A (n_0), .B (can_tx_inst_shift_reg[36]), .Z
       (n_372));
  NAND2X1 g8780__9315(.A (n_0), .B (can_tx_inst_shift_reg[33]), .Z
       (n_371));
  NAND3X1 g8781__9945(.A (n_263), .B (n_48), .C
       (uart_rx_inst_bit_count[1]), .Z (n_370));
  NAND2X1 g8782__2883(.A (n_258), .B (can_tx_inst_shift_reg[34]), .Z
       (n_369));
  NAND2X1 g8783__2346(.A (n_0), .B (can_tx_inst_shift_reg[35]), .Z
       (n_368));
  NOR2X1 g8784__1666(.A (n_51), .B (n_264), .Z (n_464));
  NAND2X1 g8790__7410(.A (n_258), .B (can_tx_inst_shift_reg[84]), .Z
       (n_366));
  NAND2X1 g8791__6417(.A (n_0), .B (can_tx_inst_shift_reg[42]), .Z
       (n_365));
  NAND2X1 g8792__5477(.A (n_0), .B (can_tx_inst_shift_reg[43]), .Z
       (n_364));
  NAND2X1 g8793__2398(.A (n_0), .B (can_tx_inst_shift_reg[44]), .Z
       (n_363));
  NAND2X1 g8794__5107(.A (n_0), .B (can_tx_inst_shift_reg[45]), .Z
       (n_362));
  NAND2X1 g8795__6260(.A (n_258), .B (can_tx_inst_shift_reg[46]), .Z
       (n_361));
  NAND2X1 g8796__4319(.A (n_258), .B (can_tx_inst_shift_reg[47]), .Z
       (n_360));
  NAND2X1 g8797__8428(.A (n_0), .B (can_tx_inst_shift_reg[48]), .Z
       (n_359));
  NAND2X1 g8798__5526(.A (n_258), .B (can_tx_inst_shift_reg[49]), .Z
       (n_358));
  NAND2X1 g8799__6783(.A (n_258), .B (can_tx_inst_shift_reg[50]), .Z
       (n_357));
  NAND2X1 g8800__3680(.A (n_0), .B (can_tx_inst_shift_reg[51]), .Z
       (n_356));
  OR2X1 g8801__1617(.A (n_31), .B (n_262), .Z (n_355));
  NAND2X1 g8802__2802(.A (n_258), .B (can_tx_inst_shift_reg[52]), .Z
       (n_354));
  NAND2X1 g8803__1705(.A (n_0), .B (can_tx_inst_shift_reg[53]), .Z
       (n_353));
  NAND2X1 g8804__5122(.A (n_0), .B (can_tx_inst_shift_reg[54]), .Z
       (n_352));
  NAND2X1 g8805__8246(.A (n_258), .B (can_tx_inst_shift_reg[55]), .Z
       (n_351));
  NAND2X1 g8806__7098(.A (n_258), .B (can_tx_inst_shift_reg[56]), .Z
       (n_350));
  NAND2X1 g8807__6131(.A (n_258), .B (can_tx_inst_shift_reg[57]), .Z
       (n_349));
  NAND2X1 g8808__1881(.A (n_0), .B (can_tx_inst_shift_reg[58]), .Z
       (n_348));
  MUX2X1 g8809__5115(.A (n_150), .B (n_242), .S
       (uart_rx_inst_bit_count[0]), .Z (n_347));
  NAND2X1 g8810__7482(.A (n_258), .B (can_tx_inst_shift_reg[59]), .Z
       (n_346));
  NAND2X1 g8811__4733(.A (n_0), .B (can_tx_inst_shift_reg[60]), .Z
       (n_345));
  NAND2X1 g8812__6161(.A (n_0), .B (can_tx_inst_shift_reg[61]), .Z
       (n_344));
  NAND2X1 g8813__9315(.A (n_258), .B (can_tx_inst_shift_reg[62]), .Z
       (n_343));
  NAND2X1 g8814__9945(.A (n_0), .B (can_tx_inst_shift_reg[63]), .Z
       (n_342));
  NAND2X1 g8815__2883(.A (n_258), .B (can_tx_inst_shift_reg[64]), .Z
       (n_341));
  NAND2X1 g8816__2346(.A (n_258), .B (can_tx_inst_shift_reg[65]), .Z
       (n_340));
  NAND2X1 g8817__1666(.A (n_258), .B (can_tx_inst_shift_reg[66]), .Z
       (n_339));
  NAND2X1 g8818__7410(.A (n_258), .B (can_tx_inst_shift_reg[67]), .Z
       (n_338));
  NAND2X1 g8819__6417(.A (n_258), .B (can_tx_inst_shift_reg[68]), .Z
       (n_337));
  NAND2X1 g8820__5477(.A (n_258), .B (can_tx_inst_shift_reg[69]), .Z
       (n_336));
  NAND2X1 g8821__2398(.A (n_258), .B (can_tx_inst_shift_reg[70]), .Z
       (n_335));
  NAND2X1 g8822__5107(.A (n_258), .B (can_tx_inst_shift_reg[71]), .Z
       (n_334));
  NAND2X1 g8823__6260(.A (n_0), .B (can_tx_inst_shift_reg[72]), .Z
       (n_333));
  NAND2X1 g8824__4319(.A (n_0), .B (can_tx_inst_shift_reg[73]), .Z
       (n_332));
  NAND2X1 g8825__8428(.A (n_0), .B (can_tx_inst_shift_reg[74]), .Z
       (n_331));
  NAND2X1 g8826__5526(.A (n_0), .B (can_tx_inst_shift_reg[75]), .Z
       (n_330));
  NAND2X1 g8827__6783(.A (n_0), .B (can_tx_inst_shift_reg[11]), .Z
       (n_329));
  NAND2X1 g8828__3680(.A (n_258), .B (can_tx_inst_shift_reg[76]), .Z
       (n_328));
  NAND2X1 g8829__1617(.A (n_258), .B (can_tx_inst_shift_reg[77]), .Z
       (n_327));
  NAND2X1 g8830__2802(.A (n_0), .B (can_tx_inst_shift_reg[12]), .Z
       (n_326));
  NAND2X1 g8831__1705(.A (n_0), .B (can_tx_inst_shift_reg[78]), .Z
       (n_325));
  NAND2X1 g8832__5122(.A (n_0), .B (can_tx_inst_shift_reg[79]), .Z
       (n_324));
  NAND2X1 g8833__8246(.A (n_258), .B (can_tx_inst_shift_reg[80]), .Z
       (n_323));
  NAND2X1 g8834__7098(.A (n_0), .B (can_tx_inst_shift_reg[13]), .Z
       (n_322));
  NAND2X1 g8835__6131(.A (n_258), .B (can_tx_inst_shift_reg[14]), .Z
       (n_321));
  NAND2X1 g8836__1881(.A (n_258), .B (can_tx_inst_shift_reg[81]), .Z
       (n_320));
  NAND2X1 g8837__5115(.A (n_258), .B (can_tx_inst_shift_reg[15]), .Z
       (n_319));
  NAND2X1 g8838__7482(.A (n_258), .B (can_tx_inst_shift_reg[82]), .Z
       (n_318));
  NAND2X1 g8839__4733(.A (n_0), .B (can_tx_inst_shift_reg[83]), .Z
       (n_317));
  NAND2X1 g8840__6161(.A (n_0), .B (can_tx_inst_shift_reg[16]), .Z
       (n_316));
  NAND2X1 g8841__9315(.A (n_258), .B (can_tx_inst_shift_reg[41]), .Z
       (n_315));
  NAND2X1 g8842__9945(.A (n_258), .B (can_tx_inst_shift_reg[85]), .Z
       (n_314));
  NAND2X1 g8843__2883(.A (n_258), .B (can_tx_inst_shift_reg[86]), .Z
       (n_313));
  NAND2X1 g8844__2346(.A (n_258), .B (can_tx_inst_shift_reg[17]), .Z
       (n_312));
  NAND2X1 g8845__1666(.A (n_258), .B (can_tx_inst_shift_reg[18]), .Z
       (n_311));
  NAND2X1 g8846__7410(.A (n_258), .B (can_tx_inst_shift_reg[87]), .Z
       (n_310));
  NAND2X1 g8847__6417(.A (n_258), .B (can_tx_inst_shift_reg[88]), .Z
       (n_309));
  NAND2X1 g8848__5477(.A (n_0), .B (can_tx_inst_shift_reg[89]), .Z
       (n_308));
  NAND2X1 g8849__2398(.A (n_258), .B (can_tx_inst_shift_reg[19]), .Z
       (n_307));
  NAND2X1 g8850__5107(.A (n_258), .B (can_tx_inst_shift_reg[20]), .Z
       (n_306));
  NAND2X1 g8851__6260(.A (n_258), .B (can_tx_inst_shift_reg[90]), .Z
       (n_305));
  NAND2X1 g8852__4319(.A (n_258), .B (can_tx_inst_shift_reg[91]), .Z
       (n_304));
  NAND2X1 g8853__8428(.A (n_258), .B (can_tx_inst_shift_reg[92]), .Z
       (n_303));
  NAND2X1 g8854__5526(.A (n_0), .B (can_tx_inst_shift_reg[93]), .Z
       (n_302));
  NAND2X1 g8855__6783(.A (n_258), .B (can_tx_inst_shift_reg[21]), .Z
       (n_301));
  NAND2X1 g8856__3680(.A (n_0), .B (can_tx_inst_shift_reg[94]), .Z
       (n_300));
  NAND2X1 g8857__1617(.A (n_0), .B (can_tx_inst_shift_reg[95]), .Z
       (n_299));
  NAND2X1 g8858__2802(.A (n_258), .B (can_tx_inst_shift_reg[96]), .Z
       (n_298));
  NAND2X1 g8859__1705(.A (n_0), .B (can_tx_inst_shift_reg[97]), .Z
       (n_297));
  NAND2X1 g8860__5122(.A (n_0), .B (can_tx_inst_shift_reg[22]), .Z
       (n_296));
  NAND2X1 g8861__8246(.A (n_0), .B (can_tx_inst_shift_reg[98]), .Z
       (n_295));
  NAND2X1 g8862__7098(.A (n_0), .B (can_tx_inst_shift_reg[23]), .Z
       (n_294));
  NAND2X1 g8863__6131(.A (n_0), .B (can_tx_inst_shift_reg[100]), .Z
       (n_293));
  NAND2X1 g8864__1881(.A (n_0), .B (can_tx_inst_shift_reg[101]), .Z
       (n_292));
  NAND2X1 g8865__5115(.A (n_0), .B (can_tx_inst_shift_reg[24]), .Z
       (n_291));
  NAND2X1 g8866__7482(.A (n_253), .B (n_3), .Z (n_290));
  NAND3X1 g8867__4733(.A (n_261), .B (n_15), .C
       (can_tx_inst_status_reg[4]), .Z (n_289));
  NAND3X1 g8868__6161(.A (n_11), .B (n_231), .C (n_49), .Z (n_288));
  NAND3X1 g8869__9315(.A (n_11), .B (n_229), .C (n_43), .Z (n_287));
  NAND3X1 g8870__9945(.A (n_11), .B (n_228), .C (n_57), .Z (n_286));
  NAND3X1 g8871__2883(.A (n_11), .B (n_161), .C (n_42), .Z (n_285));
  NAND3X1 g8872__2346(.A (n_11), .B (n_200), .C (n_45), .Z (n_284));
  NAND3X1 g8873__1666(.A (n_11), .B (n_216), .C (n_47), .Z (n_283));
  NOR2X1 g8874__7410(.A (n_254), .B (n_262), .Z (n_282));
  MUX2X1 g8875__6417(.A (uart_rx_inst_shift_reg[2]), .B
       (uart_rx_inst_shift_reg[1]), .S (n_149), .Z (n_281));
  MUX2X1 g8876__5477(.A (uart_rx_inst_shift_reg[3]), .B
       (uart_rx_inst_shift_reg[2]), .S (n_149), .Z (n_280));
  MUX2X1 g8877__2398(.A (uart_rx_inst_shift_reg[4]), .B
       (uart_rx_inst_shift_reg[3]), .S (n_149), .Z (n_279));
  MUX2X1 g8878__5107(.A (uart_rx_inst_shift_reg[5]), .B
       (uart_rx_inst_shift_reg[4]), .S (n_149), .Z (n_278));
  MUX2X1 g8879__6260(.A (uart_rx_inst_shift_reg[6]), .B
       (uart_rx_inst_shift_reg[5]), .S (n_149), .Z (n_277));
  MUX2X1 g8880__4319(.A (uart_rx_inst_shift_reg[8]), .B
       (uart_rx_inst_shift_reg[7]), .S (n_149), .Z (n_276));
  MUX2X1 g8881__8428(.A (uart_rx_inst_shift_reg[9]), .B
       (uart_rx_inst_shift_reg[8]), .S (n_149), .Z (n_275));
  MUX2X1 g8882__5526(.A (Serial_in), .B (uart_rx_inst_shift_reg[9]), .S
       (n_149), .Z (n_274));
  MUX2X1 g8883__6783(.A (uart_rx_inst_shift_reg[7]), .B
       (uart_rx_inst_shift_reg[6]), .S (n_149), .Z (n_273));
  MUX2X1 g8884__3680(.A (uart_rx_inst_shift_reg[8]), .B
       (uart_rx_data_bus[7]), .S (n_151), .Z (n_272));
  MUX2X1 g8885__1617(.A (uart_rx_inst_shift_reg[1]), .B
       (uart_rx_data_bus[0]), .S (n_151), .Z (n_271));
  MUX2X1 g8886__2802(.A (uart_rx_inst_shift_reg[2]), .B
       (uart_rx_data_bus[1]), .S (n_151), .Z (n_270));
  MUX2X1 g8887__1705(.A (uart_rx_inst_shift_reg[3]), .B
       (uart_rx_data_bus[2]), .S (n_151), .Z (n_269));
  MUX2X1 g8888__5122(.A (uart_rx_inst_shift_reg[5]), .B
       (uart_rx_data_bus[4]), .S (n_151), .Z (n_268));
  MUX2X1 g8889__8246(.A (uart_rx_inst_shift_reg[6]), .B
       (uart_rx_data_bus[5]), .S (n_151), .Z (n_267));
  MUX2X1 g8890__7098(.A (uart_rx_inst_shift_reg[7]), .B
       (uart_rx_data_bus[6]), .S (n_151), .Z (n_266));
  MUX2X1 g8891__6131(.A (uart_rx_inst_shift_reg[4]), .B
       (uart_rx_data_bus[3]), .S (n_151), .Z (n_265));
  NAND2X1 g8892__1881(.A (n_11), .B (n_593), .Z (n_367));
  INVX16 g8936(.A (n_11), .Z (n_259));
  INVX8 g8942(.A (n_10), .Z (n_11));
  INVX4 g8943(.A (n_243), .Z (n_258));
  NAND2X1 g8944__5115(.A (n_151), .B (n_190), .Z (n_257));
  OR2X1 g8945__7482(.A (can_tx_inst_status_reg[4]), .B (n_237), .Z
       (n_256));
  NAND2X1 g8946__4733(.A (n_239), .B (can_tx_inst_status_reg[3]), .Z
       (n_255));
  NOR2X1 g8947__6161(.A (can_index[2]), .B (n_240), .Z (n_254));
  NAND2X1 g8948__9315(.A (n_238), .B (n_5), .Z (n_253));
  XOR2X1 g8949__9945(.A (uart_rx_inst_state[1]), .B (n_59), .Z (n_252));
  NAND2X1 g8951__2346(.A (n_150), .B (uart_rx_inst_bit_count[3]), .Z
       (n_250));
  NAND2X1 g8952__1666(.A (n_58), .B (n_128), .Z (n_249));
  NAND2X1 g8953__7410(.A (n_9), .B (n_178), .Z (n_248));
  NAND3X1 g8954__6417(.A (n_8), .B (n_239), .C (n_19), .Z (n_247));
  MUX2X1 g8955__5477(.A (n_8), .B (n_4), .S
       (can_tx_inst_status_reg[0]), .Z (n_246));
  NAND2X1 g8956__2398(.A (n_232), .B (n_3), .Z (n_245));
  NOR2X1 g8957__5107(.A (n_233), .B (n_240), .Z (n_244));
  OR2X1 g8958__6260(.A (n_52), .B (n_242), .Z (n_264));
  AND2X1 g8966__4319(.A (n_150), .B (uart_rx_inst_bit_count[0]), .Z
       (n_263));
  AND2X1 g8971__8428(.A (n_240), .B (can_index[2]), .Z (n_262));
  NOR2X1 g8983__5526(.A (n_238), .B (n_189), .Z (n_261));
  NAND2X1 g8984__6783(.A (n_187), .B (n_5), .Z (n_260));
  NOR2X1 g8985__3680(.A (n_3), .B (n_241), .Z (n_10));
  NAND2X1 g8986__1617(.A (n_241), .B (n_4), .Z (n_243));
  INVX2 g8987(.A (n_239), .Z (n_238));
  NOR2X1 g8988__2802(.A (n_19), .B (n_29), .Z (n_237));
  NAND2X1 g8989__1705(.A (n_8), .B (can_tx_inst_shift_reg[16]), .Z
       (n_236));
  NAND2X1 g8990__5122(.A (n_35), .B (n_17), .Z (n_235));
  NAND2X1 g8991__8246(.A (n_8), .B (can_tx_inst_shift_reg[15]), .Z
       (n_234));
  NOR2X1 g8992__7098(.A (can_index[1]), .B (n_39), .Z (n_233));
  NAND2X1 g8993__6131(.A (n_5), .B (n_38), .Z (n_232));
  NAND2X1 g8994__1881(.A (n_8), .B (can_tx_inst_shift_reg[104]), .Z
       (n_231));
  NAND2X1 g8995__5115(.A (n_9), .B (can_tx_inst_shift_reg[25]), .Z
       (n_230));
  NAND2X1 g8996__7482(.A (n_7), .B (can_tx_inst_shift_reg[105]), .Z
       (n_229));
  NAND2X1 g8997__4733(.A (n_8), .B (can_tx_inst_shift_reg[106]), .Z
       (n_228));
  NAND2X1 g8998__6161(.A (n_9), .B (can_tx_inst_shift_reg[26]), .Z
       (n_227));
  NAND2X1 g8999__9315(.A (n_9), .B (can_tx_inst_shift_reg[82]), .Z
       (n_226));
  NAND2X1 g9000__9945(.A (n_9), .B (can_tx_inst_shift_reg[27]), .Z
       (n_225));
  NAND2X1 g9001__2883(.A (n_22), .B (n_3), .Z (n_224));
  NAND2X1 g9003__1666(.A (n_7), .B (can_tx_inst_shift_reg[28]), .Z
       (n_222));
  NAND2X1 g9004__7410(.A (n_9), .B (can_tx_inst_shift_reg[40]), .Z
       (n_221));
  NAND2X1 g9005__6417(.A (n_9), .B (can_tx_inst_shift_reg[31]), .Z
       (n_220));
  NAND2X1 g9006__5477(.A (n_9), .B (can_tx_inst_shift_reg[32]), .Z
       (n_219));
  NAND2X1 g9007__2398(.A (n_9), .B (can_tx_inst_shift_reg[81]), .Z
       (n_218));
  NAND2X1 g9008__5107(.A (n_8), .B (can_tx_inst_shift_reg[34]), .Z
       (n_217));
  NAND2X1 g9009__6260(.A (n_8), .B (can_tx_inst_shift_reg[103]), .Z
       (n_216));
  NAND2X1 g9010__4319(.A (n_9), .B (can_tx_inst_shift_reg[35]), .Z
       (n_215));
  NAND2X1 g9011__8428(.A (n_8), .B (can_tx_inst_shift_reg[41]), .Z
       (n_214));
  NAND2X1 g9012__5526(.A (n_9), .B (can_tx_inst_shift_reg[42]), .Z
       (n_213));
  NAND2X1 g9013__6783(.A (n_8), .B (can_tx_inst_shift_reg[43]), .Z
       (n_212));
  NAND2X1 g9014__3680(.A (n_8), .B (can_tx_inst_shift_reg[101]), .Z
       (n_211));
  NAND2X1 g9015__1617(.A (n_8), .B (can_tx_inst_shift_reg[44]), .Z
       (n_210));
  NAND2X1 g9016__2802(.A (n_8), .B (can_tx_inst_shift_reg[30]), .Z
       (n_209));
  NAND2X1 g9017__1705(.A (n_9), .B (can_tx_inst_shift_reg[45]), .Z
       (n_208));
  NAND2X1 g9018__5122(.A (n_8), .B (can_tx_inst_shift_reg[14]), .Z
       (n_207));
  NAND2X1 g9019__8246(.A (n_9), .B (can_tx_inst_shift_reg[46]), .Z
       (n_206));
  NAND2X1 g9020__7098(.A (n_9), .B (can_tx_inst_shift_reg[39]), .Z
       (n_205));
  NAND2X1 g9021__6131(.A (n_9), .B (can_tx_inst_shift_reg[47]), .Z
       (n_204));
  NAND2X1 g9022__1881(.A (n_8), .B (can_tx_inst_shift_reg[48]), .Z
       (n_203));
  NAND2X1 g9023__5115(.A (n_8), .B (can_tx_inst_shift_reg[49]), .Z
       (n_202));
  NAND2X1 g9024__7482(.A (n_8), .B (can_tx_inst_shift_reg[50]), .Z
       (n_201));
  NAND2X1 g9025__4733(.A (n_8), .B (can_tx_inst_shift_reg[100]), .Z
       (n_200));
  NAND2X1 g9026__6161(.A (n_9), .B (can_tx_inst_shift_reg[51]), .Z
       (n_199));
  NAND2X1 g9027__9315(.A (n_9), .B (can_tx_inst_shift_reg[52]), .Z
       (n_198));
  NAND2X1 g9028__9945(.A (n_8), .B (can_tx_inst_shift_reg[86]), .Z
       (n_197));
  NAND2X1 g9029__2883(.A (n_9), .B (can_tx_inst_shift_reg[53]), .Z
       (n_196));
  NAND2X1 g9030__2346(.A (n_9), .B (can_tx_inst_shift_reg[12]), .Z
       (n_195));
  NAND2X1 g9031__1666(.A (n_9), .B (can_tx_inst_shift_reg[54]), .Z
       (n_194));
  NAND2X1 g9032__7410(.A (n_9), .B (can_tx_inst_shift_reg[55]), .Z
       (n_193));
  NAND2X1 g9033__6417(.A (n_9), .B (can_tx_inst_shift_reg[56]), .Z
       (n_192));
  NAND2X1 g9034__5477(.A (n_9), .B (can_tx_inst_shift_reg[33]), .Z
       (n_191));
  OR2X1 g9035__2398(.A (n_23), .B (n_2), .Z (n_190));
  NAND2X1 g9036__5107(.A (n_7), .B (can_tx_inst_status_reg[3]), .Z
       (n_189));
  NAND2X1 g9037__6260(.A (n_9), .B (can_tx_inst_shift_reg[57]), .Z
       (n_188));
  NAND2X1 g9038__4319(.A (n_4), .B (n_40), .Z (n_187));
  NAND2X1 g9039__8428(.A (n_9), .B (can_tx_inst_shift_reg[58]), .Z
       (n_186));
  NAND2X1 g9040__5526(.A (n_9), .B (can_tx_inst_shift_reg[38]), .Z
       (n_185));
  NAND2X1 g9041__6783(.A (n_9), .B (can_tx_inst_shift_reg[59]), .Z
       (n_184));
  NAND2X1 g9042__3680(.A (n_9), .B (can_tx_inst_shift_reg[60]), .Z
       (n_183));
  NAND2X1 g9043__1617(.A (n_8), .B (can_tx_inst_shift_reg[92]), .Z
       (n_182));
  NAND2X1 g9044__2802(.A (n_8), .B (can_tx_inst_shift_reg[61]), .Z
       (n_181));
  NAND2X1 g9045__1705(.A (n_9), .B (can_tx_inst_shift_reg[62]), .Z
       (n_180));
  NAND2X1 g9046__5122(.A (n_9), .B (can_tx_inst_shift_reg[63]), .Z
       (n_179));
  NOR2X1 g9047__8246(.A (can_tx_inst_status_reg[2]), .B (n_38), .Z
       (n_178));
  NAND2X1 g9048__7098(.A (n_9), .B (can_tx_inst_shift_reg[64]), .Z
       (n_177));
  NAND2X1 g9049__6131(.A (n_8), .B (can_tx_inst_shift_reg[97]), .Z
       (n_176));
  NAND2X1 g9050__1881(.A (n_9), .B (can_tx_inst_shift_reg[65]), .Z
       (n_175));
  NAND2X1 g9051__5115(.A (n_9), .B (can_tx_inst_shift_reg[66]), .Z
       (n_174));
  NAND2X1 g9052__7482(.A (n_9), .B (can_tx_inst_shift_reg[67]), .Z
       (n_173));
  NAND2X1 g9053__4733(.A (n_9), .B (can_tx_inst_shift_reg[29]), .Z
       (n_172));
  NAND2X1 g9054__6161(.A (n_9), .B (can_tx_inst_shift_reg[68]), .Z
       (n_171));
  NAND2X1 g9055__9315(.A (n_8), .B (can_tx_inst_shift_reg[69]), .Z
       (n_170));
  NAND2X1 g9056__9945(.A (n_7), .B (can_tx_inst_shift_reg[36]), .Z
       (n_169));
  NAND2X1 g9057__2883(.A (n_9), .B (can_tx_inst_shift_reg[70]), .Z
       (n_168));
  NAND2X1 g9058__2346(.A (n_8), .B (can_tx_inst_shift_reg[37]), .Z
       (n_167));
  NAND2X1 g9059__1666(.A (n_9), .B (can_tx_inst_shift_reg[71]), .Z
       (n_166));
  NAND2X1 g9060__7410(.A (n_8), .B (can_tx_inst_shift_reg[72]), .Z
       (n_165));
  NAND2X1 g9061__6417(.A (n_8), .B (can_tx_inst_shift_reg[73]), .Z
       (n_164));
  NAND2X1 g9062__5477(.A (n_9), .B (can_tx_inst_shift_reg[74]), .Z
       (n_163));
  NAND2X1 g9063__2398(.A (n_9), .B (can_tx_inst_shift_reg[22]), .Z
       (n_162));
  NAND2X1 g9064__5107(.A (n_7), .B (can_tx_inst_shift_reg[11]), .Z
       (n_161));
  NAND2X1 g9065__6260(.A (n_9), .B (can_tx_inst_shift_reg[75]), .Z
       (n_160));
  NAND2X1 g9066__4319(.A (n_9), .B (can_tx_inst_shift_reg[76]), .Z
       (n_159));
  NAND2X1 g9067__8428(.A (n_9), .B (can_tx_inst_shift_reg[77]), .Z
       (n_158));
  NAND2X1 g9068__5526(.A (n_9), .B (can_tx_inst_shift_reg[21]), .Z
       (n_157));
  NAND2X1 g9069__6783(.A (n_9), .B (can_tx_inst_shift_reg[78]), .Z
       (n_156));
  NAND2X1 g9070__3680(.A (n_8), .B (can_tx_inst_shift_reg[13]), .Z
       (n_155));
  NAND2X1 g9071__1617(.A (n_8), .B (can_tx_inst_shift_reg[79]), .Z
       (n_154));
  NAND2X1 g9072__2802(.A (n_8), .B (can_tx_inst_shift_reg[94]), .Z
       (n_153));
  NAND2X1 g9073__1705(.A (n_9), .B (can_tx_inst_shift_reg[80]), .Z
       (n_152));
  OR2X1 g9074__5122(.A (uart_rx_inst_state[0]), .B (n_53), .Z (n_242));
  NAND2X1 g9075__8246(.A (n_41), .B (n_5), .Z (n_241));
  AND2X1 g9076__7098(.A (n_39), .B (can_index[1]), .Z (n_240));
  AND2X1 g9077__6131(.A (n_37), .B (can_tx_inst_status_reg[2]), .Z
       (n_239));
  INVX2 g9078(.A (n_150), .Z (n_149));
  MUX2X1 g9079__1881(.A (can_tx_inst_shift_reg[4]), .B
       (can_tx_inst_shift_reg[5]), .S (n_3), .Z (n_148));
  NAND2X1 g9080__5115(.A (n_8), .B (can_tx_inst_shift_reg[17]), .Z
       (n_147));
  NAND2X1 g9081__7482(.A (n_9), .B (can_tx_inst_shift_reg[84]), .Z
       (n_146));
  NAND2X1 g9082__4733(.A (n_8), .B (can_tx_inst_shift_reg[85]), .Z
       (n_145));
  NAND2X1 g9083__6161(.A (n_8), .B (can_tx_inst_shift_reg[18]), .Z
       (n_144));
  NAND2X1 g9084__9315(.A (n_8), .B (can_tx_inst_shift_reg[87]), .Z
       (n_143));
  NAND2X1 g9085__9945(.A (n_8), .B (can_tx_inst_shift_reg[88]), .Z
       (n_142));
  NAND2X1 g9086__2883(.A (n_8), .B (can_tx_inst_shift_reg[19]), .Z
       (n_141));
  NAND2X1 g9087__2346(.A (n_8), .B (can_tx_inst_shift_reg[20]), .Z
       (n_140));
  NAND2X1 g9088__1666(.A (n_8), .B (can_tx_inst_shift_reg[90]), .Z
       (n_139));
  NAND2X1 g9089__7410(.A (n_8), .B (can_tx_inst_shift_reg[91]), .Z
       (n_138));
  NAND2X1 g9090__6417(.A (n_8), .B (can_tx_inst_shift_reg[93]), .Z
       (n_137));
  NAND2X1 g9091__5477(.A (n_8), .B (can_tx_inst_shift_reg[95]), .Z
       (n_136));
  NAND2X1 g9092__2398(.A (n_8), .B (can_tx_inst_shift_reg[96]), .Z
       (n_135));
  NAND2X1 g9093__5107(.A (n_8), .B (can_tx_inst_shift_reg[89]), .Z
       (n_134));
  NAND2X1 g9094__6260(.A (n_8), .B (can_tx_inst_shift_reg[98]), .Z
       (n_133));
  NAND2X1 g9095__4319(.A (n_8), .B (can_tx_inst_shift_reg[23]), .Z
       (n_132));
  NAND2X1 g9096__8428(.A (n_8), .B (can_tx_inst_shift_reg[99]), .Z
       (n_131));
  NAND2X1 g9097__5526(.A (n_8), .B (can_tx_inst_shift_reg[24]), .Z
       (n_130));
  NAND2X1 g9098__6783(.A (n_8), .B (can_tx_inst_shift_reg[102]), .Z
       (n_129));
  NAND3X1 g9099__3680(.A (n_4), .B (can_tx_inst_state[0]), .C
       (Can_ID_Bus[0]), .Z (n_128));
  NAND2X1 g9100__1617(.A (n_9), .B (can_tx_inst_shift_reg[83]), .Z
       (n_127));
  MUX2X1 g9101__2802(.A (can_tx_inst_shift_reg[3]), .B
       (can_tx_inst_shift_reg[4]), .S (n_3), .Z (n_126));
  NOR2X1 g9102__1705(.A (n_39), .B (n_26), .Z (n_125));
  MUX2X1 g9103__5122(.A (can_tx_data_bus[43]), .B
       (can_tx_data_bus[35]), .S (n_14), .Z (n_124));
  MUX2X1 g9104__8246(.A (can_tx_data_bus[18]), .B
       (can_tx_data_bus[10]), .S (n_1), .Z (n_123));
  MUX2X1 g9105__7098(.A (can_tx_data_bus[5]), .B (uart_rx_data_bus[5]),
       .S (n_14), .Z (n_122));
  MUX2X1 g9106__6131(.A (can_tx_data_bus[48]), .B
       (can_tx_data_bus[40]), .S (n_1), .Z (n_121));
  MUX2X1 g9107__1881(.A (can_tx_data_bus[0]), .B (uart_rx_data_bus[0]),
       .S (uart_data_ready), .Z (n_120));
  MUX2X1 g9108__5115(.A (can_tx_data_bus[47]), .B
       (can_tx_data_bus[39]), .S (uart_data_ready), .Z (n_119));
  MUX2X1 g9109__7482(.A (can_tx_data_bus[6]), .B (uart_rx_data_bus[6]),
       .S (n_1), .Z (n_118));
  MUX2X1 g9110__4733(.A (can_tx_data_bus[37]), .B
       (can_tx_data_bus[29]), .S (n_1), .Z (n_117));
  MUX2X1 g9111__6161(.A (can_tx_data_bus[50]), .B
       (can_tx_data_bus[42]), .S (n_1), .Z (n_116));
  MUX2X1 g9112__9315(.A (can_tx_data_bus[21]), .B
       (can_tx_data_bus[13]), .S (n_14), .Z (n_115));
  MUX2X1 g9113__9945(.A (can_tx_data_bus[28]), .B
       (can_tx_data_bus[20]), .S (n_1), .Z (n_114));
  MUX2X1 g9114__2883(.A (can_tx_data_bus[44]), .B
       (can_tx_data_bus[36]), .S (n_14), .Z (n_113));
  MUX2X1 g9115__2346(.A (can_tx_data_bus[12]), .B (can_tx_data_bus[4]),
       .S (n_1), .Z (n_112));
  MUX2X1 g9116__1666(.A (can_tx_data_bus[52]), .B
       (can_tx_data_bus[44]), .S (n_14), .Z (n_111));
  MUX2X1 g9117__7410(.A (can_tx_data_bus[22]), .B
       (can_tx_data_bus[14]), .S (n_1), .Z (n_110));
  MUX2X1 g9118__6417(.A (can_tx_data_bus[17]), .B (can_tx_data_bus[9]),
       .S (n_1), .Z (n_109));
  MUX2X1 g9119__5477(.A (can_tx_data_bus[53]), .B
       (can_tx_data_bus[45]), .S (n_1), .Z (n_108));
  MUX2X1 g9120__2398(.A (can_tx_data_bus[23]), .B
       (can_tx_data_bus[15]), .S (n_14), .Z (n_107));
  MUX2X1 g9121__5107(.A (can_tx_data_bus[55]), .B
       (can_tx_data_bus[47]), .S (n_14), .Z (n_106));
  MUX2X1 g9122__6260(.A (can_tx_data_bus[7]), .B (uart_rx_data_bus[7]),
       .S (n_14), .Z (n_105));
  MUX2X1 g9123__4319(.A (can_tx_data_bus[1]), .B (uart_rx_data_bus[1]),
       .S (n_1), .Z (n_104));
  MUX2X1 g9124__8428(.A (can_tx_data_bus[56]), .B
       (can_tx_data_bus[48]), .S (n_14), .Z (n_103));
  MUX2X1 g9125__5526(.A (can_tx_data_bus[24]), .B
       (can_tx_data_bus[16]), .S (n_1), .Z (n_102));
  MUX2X1 g9126__6783(.A (can_tx_data_bus[57]), .B
       (can_tx_data_bus[49]), .S (n_1), .Z (n_101));
  MUX2X1 g9127__3680(.A (can_tx_data_bus[8]), .B (can_tx_data_bus[0]),
       .S (n_1), .Z (n_100));
  MUX2X1 g9128__1617(.A (can_tx_data_bus[58]), .B
       (can_tx_data_bus[50]), .S (n_1), .Z (n_99));
  MUX2X1 g9129__2802(.A (can_tx_data_bus[25]), .B
       (can_tx_data_bus[17]), .S (n_14), .Z (n_98));
  MUX2X1 g9130__1705(.A (can_tx_data_bus[59]), .B
       (can_tx_data_bus[51]), .S (n_1), .Z (n_97));
  MUX2X1 g9131__5122(.A (can_tx_data_bus[42]), .B
       (can_tx_data_bus[34]), .S (n_14), .Z (n_96));
  MUX2X1 g9132__8246(.A (can_tx_data_bus[60]), .B
       (can_tx_data_bus[52]), .S (n_1), .Z (n_95));
  MUX2X1 g9133__7098(.A (can_tx_data_bus[9]), .B (can_tx_data_bus[1]),
       .S (n_1), .Z (n_94));
  MUX2X1 g9134__6131(.A (can_tx_data_bus[26]), .B
       (can_tx_data_bus[18]), .S (n_14), .Z (n_93));
  MUX2X1 g9135__1881(.A (can_tx_data_bus[61]), .B
       (can_tx_data_bus[53]), .S (n_1), .Z (n_92));
  MUX2X1 g9136__5115(.A (can_tx_data_bus[36]), .B
       (can_tx_data_bus[28]), .S (uart_data_ready), .Z (n_91));
  MUX2X1 g9137__7482(.A (can_tx_data_bus[27]), .B
       (can_tx_data_bus[19]), .S (n_14), .Z (n_90));
  MUX2X1 g9138__4733(.A (can_tx_data_bus[62]), .B
       (can_tx_data_bus[54]), .S (n_1), .Z (n_89));
  MUX2X1 g9139__6161(.A (can_tx_data_bus[54]), .B
       (can_tx_data_bus[46]), .S (uart_data_ready), .Z (n_88));
  MUX2X1 g9140__9315(.A (can_tx_data_bus[63]), .B
       (can_tx_data_bus[55]), .S (uart_data_ready), .Z (n_87));
  MUX2X1 g9141__9945(.A (can_tx_data_bus[32]), .B
       (can_tx_data_bus[24]), .S (n_14), .Z (n_86));
  MUX2X1 g9142__2883(.A (can_tx_data_bus[2]), .B (uart_rx_data_bus[2]),
       .S (n_1), .Z (n_85));
  MUX2X1 g9143__2346(.A (can_tx_data_bus[10]), .B (can_tx_data_bus[2]),
       .S (n_1), .Z (n_84));
  MUX2X1 g9144__1666(.A (can_tx_data_bus[29]), .B
       (can_tx_data_bus[21]), .S (n_14), .Z (n_83));
  MUX2X1 g9145__7410(.A (can_tx_data_bus[20]), .B
       (can_tx_data_bus[12]), .S (n_14), .Z (n_82));
  MUX2X1 g9146__6417(.A (can_tx_data_bus[19]), .B
       (can_tx_data_bus[11]), .S (n_14), .Z (n_81));
  MUX2X1 g9147__5477(.A (can_tx_data_bus[11]), .B (can_tx_data_bus[3]),
       .S (n_1), .Z (n_80));
  MUX2X1 g9148__2398(.A (can_tx_data_bus[30]), .B
       (can_tx_data_bus[22]), .S (n_14), .Z (n_79));
  MUX2X1 g9149__5107(.A (can_tx_data_bus[31]), .B
       (can_tx_data_bus[23]), .S (n_14), .Z (n_78));
  MUX2X1 g9150__6260(.A (can_tx_data_bus[46]), .B
       (can_tx_data_bus[38]), .S (n_1), .Z (n_77));
  MUX2X1 g9151__4319(.A (can_tx_data_bus[16]), .B (can_tx_data_bus[8]),
       .S (n_14), .Z (n_76));
  MUX2X1 g9152__8428(.A (can_tx_data_bus[33]), .B
       (can_tx_data_bus[25]), .S (n_1), .Z (n_75));
  MUX2X1 g9153__5526(.A (can_tx_data_bus[4]), .B (uart_rx_data_bus[4]),
       .S (uart_data_ready), .Z (n_74));
  MUX2X1 g9154__6783(.A (can_tx_data_bus[41]), .B
       (can_tx_data_bus[33]), .S (n_14), .Z (n_73));
  MUX2X1 g9155__3680(.A (can_tx_data_bus[51]), .B
       (can_tx_data_bus[43]), .S (n_14), .Z (n_72));
  MUX2X1 g9156__1617(.A (can_tx_data_bus[3]), .B (uart_rx_data_bus[3]),
       .S (n_1), .Z (n_71));
  MUX2X1 g9157__2802(.A (can_tx_data_bus[34]), .B
       (can_tx_data_bus[26]), .S (n_14), .Z (n_70));
  MUX2X1 g9158__1705(.A (can_tx_data_bus[45]), .B
       (can_tx_data_bus[37]), .S (n_14), .Z (n_69));
  MUX2X1 g9159__5122(.A (can_tx_data_bus[35]), .B
       (can_tx_data_bus[27]), .S (n_1), .Z (n_68));
  MUX2X1 g9160__8246(.A (can_tx_data_bus[14]), .B (can_tx_data_bus[6]),
       .S (n_1), .Z (n_67));
  MUX2X1 g9161__7098(.A (can_tx_data_bus[13]), .B (can_tx_data_bus[5]),
       .S (n_1), .Z (n_66));
  MUX2X1 g9162__6131(.A (can_tx_data_bus[49]), .B
       (can_tx_data_bus[41]), .S (n_1), .Z (n_65));
  MUX2X1 g9163__1881(.A (can_tx_data_bus[38]), .B
       (can_tx_data_bus[30]), .S (n_1), .Z (n_64));
  MUX2X1 g9164__5115(.A (can_tx_data_bus[15]), .B (can_tx_data_bus[7]),
       .S (n_1), .Z (n_63));
  MUX2X1 g9165__7482(.A (can_tx_data_bus[39]), .B
       (can_tx_data_bus[31]), .S (uart_data_ready), .Z (n_62));
  MUX2X1 g9166__4733(.A (can_tx_data_bus[40]), .B
       (can_tx_data_bus[32]), .S (uart_data_ready), .Z (n_61));
  MUX2X1 g9167__6161(.A (can_tx_inst_shift_reg[1]), .B
       (can_tx_inst_shift_reg[2]), .S (n_3), .Z (n_60));
  NAND3X1 g9168__9315(.A (n_59), .B (uart_rx_inst_state[1]), .C
       (Serial_in), .Z (n_151));
  NOR2X1 g9169__9945(.A (n_17), .B (n_55), .Z (n_150));
  INVX8 g9171(.A (n_58), .Z (n_9));
  INVX2 g9172(.A (n_7), .Z (n_58));
  INVX8 g9175(.A (n_58), .Z (n_8));
  NAND2X1 g9181__2883(.A (n_4), .B (can_tx_inst_shift_reg[105]), .Z
       (n_57));
  NOR2X1 g9182__2346(.A (n_15), .B (can_tx_inst_status_reg[6]), .Z
       (n_56));
  NAND2X1 g9183__1666(.A (n_18), .B (R_byte), .Z (n_55));
  OR2X1 g9184__7410(.A (R_byte), .B (n_18), .Z (n_54));
  NOR2X1 g9185__6417(.A (R_byte), .B (n_17), .Z (n_53));
  NOR2X1 g9186__5477(.A (n_17), .B (uart_rx_inst_bit_count[0]), .Z
       (n_52));
  NOR2X1 g9187__2398(.A (n_17), .B (uart_rx_inst_bit_count[1]), .Z
       (n_51));
  NAND2X1 g9188__5107(.A (n_16), .B (uart_rx_inst_state[1]), .Z (n_50));
  NAND2X1 g9189__6260(.A (n_4), .B (can_tx_inst_shift_reg[103]), .Z
       (n_49));
  NOR2X1 g9190__4319(.A (uart_rx_inst_bit_count[3]), .B (n_16), .Z
       (n_48));
  NAND2X1 g9191__8428(.A (n_4), .B (can_tx_inst_shift_reg[102]), .Z
       (n_47));
  NAND2X1 g9192__5526(.A (n_4), .B (can_tx_inst_shift_reg[106]), .Z
       (n_46));
  NAND2X1 g9193__6783(.A (n_4), .B (can_tx_inst_shift_reg[99]), .Z
       (n_45));
  OR2X1 g9194__3680(.A (n_3), .B (n_592), .Z (n_44));
  NAND2X1 g9195__1617(.A (n_4), .B (can_tx_inst_shift_reg[104]), .Z
       (n_43));
  NAND2X1 g9196__2802(.A (n_4), .B (can_tx_inst_shift_reg[10]), .Z
       (n_42));
  AND2X1 g9197__1705(.A (uart_rx_inst_state[0]), .B (R_byte), .Z
       (n_59));
  NOR2X1 g9198__5122(.A (can_tx_inst_state[0]), .B (n_4), .Z (n_7));
  INVX2 g9199(.A (n_40), .Z (n_41));
  INVX2 g9200(.A (n_37), .Z (n_38));
  NOR2X1 g9201__8246(.A (can_tx_inst_status_reg[4]), .B
       (can_tx_inst_state[0]), .Z (n_36));
  NOR2X1 g9202__7098(.A (Serial_in), .B (uart_rx_inst_state[0]), .Z
       (n_35));
  NAND2X1 g9203__6131(.A (can_tx_inst_shift_reg[9]), .B (n_3), .Z
       (n_34));
  NAND2X1 g9204__1881(.A (can_tx_inst_shift_reg[10]), .B (n_3), .Z
       (n_33));
  NAND2X1 g9205__5115(.A (can_tx_inst_shift_reg[1]), .B (n_3), .Z
       (n_32));
  AND2X1 g9206__7482(.A (uart_data_ready), .B (Load_frame_datareg), .Z
       (n_31));
  AND2X1 g9207__4733(.A (can_tx_inst_status_reg[5]), .B
       (can_tx_inst_status_reg[6]), .Z (n_30));
  NOR2X1 g9208__6161(.A (can_tx_inst_status_reg[1]), .B
       (can_tx_inst_status_reg[2]), .Z (n_29));
  NAND2X1 g9209__9315(.A (n_15), .B (n_5), .Z (n_28));
  NAND2X1 g9210__9945(.A (can_tx_inst_shift_reg[8]), .B (n_3), .Z
       (n_27));
  NOR2X1 g9211__2883(.A (can_index[0]), .B (uart_data_ready), .Z
       (n_26));
  NAND2X1 g9212__2346(.A (can_tx_inst_shift_reg[7]), .B (n_3), .Z
       (n_25));
  NAND2X1 g9213__1666(.A (can_tx_inst_shift_reg[3]), .B (n_3), .Z
       (n_24));
  NOR2X1 g9214__7410(.A (uart_rx_inst_state[1]), .B
       (uart_rx_inst_state[0]), .Z (n_23));
  OR2X1 g9215__6417(.A (can_tx_inst_status_reg[0]), .B
       (can_tx_inst_state[0]), .Z (n_22));
  NAND2X1 g9216__5477(.A (can_tx_inst_shift_reg[6]), .B (n_3), .Z
       (n_21));
  NAND2X1 g9217__2398(.A (Load_frame_datareg), .B (Can_ID_Bus[0]), .Z
       (n_40));
  AND2X1 g9218__5107(.A (can_index[0]), .B (uart_data_ready), .Z
       (n_39));
  AND2X1 g9219__6260(.A (can_tx_inst_status_reg[0]), .B
       (can_tx_inst_status_reg[1]), .Z (n_37));
  INVX2 g9224(.A (can_tx_inst_status_reg[3]), .Z (n_19));
  INVX2 g9225(.A (uart_rx_inst_state[0]), .Z (n_18));
  INVX2 g9226(.A (uart_rx_inst_state[1]), .Z (n_17));
  INVX4 g9232(.A (can_tx_inst_state[0]), .Z (n_5));
  INVX2 g9236(.A (uart_rx_inst_bit_count[2]), .Z (n_16));
  INVX2 g9237(.A (can_tx_inst_status_reg[5]), .Z (n_15));
  INVX4 g9251(.A (n_4), .Z (n_3));
  INVX4 g9252(.A (can_tx_inst_state[1]), .Z (n_4));
  INVX2 g9260(.A (n_2), .Z (n_14));
  INVX4 g9263(.A (n_2), .Z (n_1));
  INVX2 g9264(.A (uart_data_ready), .Z (n_2));
  INVX4 drc_bufs9288(.A (n_243), .Z (n_0));
  BUFX1 g9291(.A (1'b1), .Z (Serial_out));
  MUX2X1 g2(.A (n_601), .B (n_224), .S (can_tx_inst_status_reg[1]), .Z
       (n_602));
  AND2X1 g3(.A (can_tx_inst_status_reg[0]), .B (n_9), .Z (n_601));
endmodule

